INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('821','EnergyMax Laser Sensors','Deep UV','', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('822','J-50MUV-248','Deep UV','50', '0.0005');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('823','J-50MUV-193','Deep UV','50', '0.000125');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('824','J-25MUV-193','Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('825','J-25MUV-248','Deep UV','25', '0.000125');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('826','J-50MT-10KHZ','Deep UV','50', '0.0005');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('827','J-25MT-10KHZ','Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('828','J-10MT-10KHZ','Deep UV','10', '1.0E-7');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('829','J-50MB-HE','Deep UV','50', '0.001');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('830','J-50MB-LE','Deep UV','50', '0.00025');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('831','J-25MB-LE','Deep UV','25', '2.5E-5');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('832','J-25MB-HE','Deep UV','25', '0.0005');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('833','J-10MB-HE','Deep UV','10', '1.0E-5');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('834','J-10MB-LE','Deep UV','10', '3.0E-7');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('835','J-25MB-IR','Visible','25', '0.0015');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('836','J-50MB-YAG','Deep UV','50', '0.0015');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('837','J-50MB-IR','Visible','50', '0.001');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('838','EnergyMax-USB/RS Sensors','Deep UV - IR','', '0.00E+0.00');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('839','EnergyMax-RS J-10SI-HE Energy Sensor','IR','10', '0.00E+0.00');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('840','EnergyMax-RS J-10MB-LE Energy Sensor','Deep UV','10', '5.0E-7');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('841','EnergyMax-RS J-10MB-HE Energy Sensor','Deep UV','10', '1.2E-5');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('842','EnergyMax-RS J-50MB-YAG Energy Sensor','Deep UV','50', '0.0024');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('843','EnergyMax-RS J-25MB-LE Energy Sensor','Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('844','EnergyMax-RS J-50MB-HE Energy Sensor','Deep UV','50', '0.0016');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('845','EnergyMax-RS J-50MT-10KHZ Energy Sensor','Deep UV','50', '0.0004');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('846','EnergyMax-USB J-10SI-HE Energy Sensor','IR','10', '0.00E+0.00');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('847','EnergyMax-USB J-10MB-LE Energy Sensor','Deep UV','10', '5.0E-7');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('848','EnergyMax-USB J-10MB-HE Energy Sensor','Deep UV','10', '1.2E-5');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('849','EnergyMax-USB J-50MB-YAG Energy Sensor','Deep UV','50', '0.0024');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('850','EnergyMax-USB J-25MB-LE Energy Sensor','Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('851','EnergyMax-USB J-25MB-HE Energy Sensor','Deep UV','25', '0.00085');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('852','EnergyMax-USB J-50MB-LE Energy Sensor','Deep UV','50', '0.0004');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('853','EnergyMax-USB J-50MB-HE Energy Sensor','Deep UV','50', '0.0016');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('854','EnergyMax-USB J-10MT 10KHZ Energy Sensor','Deep UV','10', '3.0E-7');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('855','EnergyMax-USB J-25MT-10KHZ Energy Sensor','Deep UV','25', '9.0E-5');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('856','EnergyMax-USB J-50MT-10KHZ Energy Sensor','Deep UV','50', '0.0004');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('857','EnergyMax-USB J-25MUV-193 Energy Sensor','Deep UV','25', '9.0E-5');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('858','EnergyMax-USB J-50MUV-248 with Diffuser Energy Sensor','Deep UV','50', '0.0008');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('860','BM Mount','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('867','LaserCam-HR II','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('868','LaserCam-HR II 1/2"','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('869','LaserCam-HR II 2/3"','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('870','LaserCam-HR-InGaAs','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('871','LaserCam-HR-UV','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('872','ModeMaster PC M-Squared (M2) Beam Propagation Analyzer','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('873','ModeMaster PC System UV, Low-Divergence','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('874','ModeMaster PC system, UV, High-Divergence','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('875','ModeMaster PC System VIS Low-Divergence','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('876','ModeMaster PC System, VIs, High-Divergence','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('877','ModeMaster PC System, NIR, Low-Divergence','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('878','ModeMaster PC System, NIR, High-Divergence','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('879','ModeMaster PC System, IR High Divergence','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('880','ModeMaster PC System, IR Low Divergence','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('881','WaveMaster','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('887','Laser Power and Energy Meters','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('888','LabMax-TOP','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('889','LabMax-Pro SSIM','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('890','LabMaxTOP with GPIB','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('891','LabMax-TO','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('892','FieldMaxII-TOP','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('893','FieldMaxII-P','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('894','FieldMaxII To','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('895','FieldMate','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('896','Laser Check','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('897','S-1592 Android Mobile System Bundle','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('898','S-1593 iOS Mobile System Bundle','','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('899','Sensors - Laser Power','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('900','PM10','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('901','PM30','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('902','PM2','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('903','PM150-50','Visible','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('904','PM150','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('905','PM10X','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('906','PM150X','Visible','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('907','PM2X','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('908','PM100-19C','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('909','PM30X','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('910','PM300F-50','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('911','PM200F-50','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('912','PM200F-19','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('913','PM300F-50X','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('914','PM300F-19','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('915','PM200F-50X','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('916','PM1K','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('917','PM5K','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('918','PM3K','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('919','PM300','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('920','LM-2 VIS','Violet','7.9', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('921','OP-2 VIS','Violet','7.9', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('922','LM-2 IR','Near IR','5', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('923','LM-2 UV','Deep UV','6', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('924','OP-2 UV','Deep UV','6', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('925','OP-2 IR','Near IR','5', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('926','PM3','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('927','PS19Q','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('928','PS10','Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('929','PS10Q','Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('930','PS19Q','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('931','PM3Q','Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('932','PM5K-100','Deep UV','100', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('933','PM1K-100','Deep UV','100', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('934','PM5K-200','Deep UV','200', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('935','PM3K-100','Deep UV','100', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('936','PM150-19B','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('937','PM1K-36B','Deep UV','36', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('938','PM10-19A','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('939','PM10-19B','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('940','PM150-50B','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('941','PM150-19A','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('942','BeamFinder','Deep UV','35', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('943','PM150-50XB','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('944','PM150-50A','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('945','PM10V1','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('946','PM30V1','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('947','LM-10 HTD','Deep UV','16', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('948','LM-45 HTD','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('949','LM-3 HTD','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('950','LM-100 HTD','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('951','LM-150FS HTD','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('952','LM-1000','Deep UV','38', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('953','LM-5000','Deep UV','55', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('954','LM-2500','Deep UV','55', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('955','PM10-19C','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('956','PM150-50C','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('957','PM150-50XC','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('958','PM150-19C','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('959','PowerMax-Pro Sensor','Deep UV - Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('960','PowerMax-Pro 150F HD','UV','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('961','PowerMax-Pro 150 HD','UV','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('962','PowerMax-Pro HP','Near IR','25 (diameter)', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('963','PowerMax-Pro 150F BB','Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('964','PowerMax-Pro 150 BB','Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('965','PowerMax-Pro 150 HD Nano','Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('966','PowerMax-Pro 150 BB Nano','Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('967','PowerMax-Pro 150F Nano','Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('968','PowerMax-Pro USB/RS Sensors','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('969','PowerMax-Pro USB/RS 150 HD','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('970','PowerMax-Pro USB/RS 150 HD Nano','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('971','PowerMax-Pro USB/RS 150F HD','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('972','PowerMax-Pro USB/RS 150F HD Nano','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('973','PowerMax-Pro USB/RS 150 BB','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('974','PowerMax-Pro USB/RS 150F BB','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('975','kW PowerMax-Pro Sensor','Near IR - IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('976','PMP 1kW','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('977','PMP 1kW','IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('978','PMP 1kW','IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('979','PMP 1kW','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('980','PMP 1kW','IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('981','PMP 3kW','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('982','PMP 3kW','IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('983','PMP 3kW','IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('984','PMP 3kW','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('985','PMP 3kW','IR','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('986','PowerMax USB/RS Sensors','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('987','PowerMax-USB LM-10 Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('988','PowerMax-USB LM-1000 Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('989','PowerMax-USB LM-20 Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('990','PowerMax-USB LM-200 110V Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('991','PowerMax-USB LM-200 220V Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('993','PowerMax-USB LM-3 Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('994','PowerMax-USB LM-45 Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('995','PowerMax-USB LM-5000 Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('996','PowerMax-USB PM10 Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('997','PowerMax-USB PM10-19C Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('998','PowerMax-USB PM150-19C Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('999','PowerMax-USB PM150-50C Power Sensor Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1000','PowerMax-USB PM1K-36C Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1001','PowerMax-USB PM2 Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1002','PowerMax-USB PM3 Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1003','PowerMax-USB PM30 Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1004','PowerMax-USB PM3Q Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1005','PowerMax-USB PS10 Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1006','PowerMax-USB PS19 Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1007','PowerMax-USB PS19Q Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1008','PowerMax-USB UV/VIS Quantum Power Sensors','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1009','PowerMax-USB Wand UV/VIS Quantum Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1010','PowerMax-RS PM10-19C Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1011','PowerMax-RS PM150-19C Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1012','PowerMax-RS PM150-50C Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1013','PowerMax-RS PM30 Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1014','PowerMax-RS PM1K-36C Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1015','PowerMax-RS PS19Q Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1016','PowerMax-RS PM3K Power Sensor','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1043','AC Power Adapter','','', '');
