INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('248','OBIS Lasers','UV - Near IR','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('249','OBIS LX/LS','Violet - Near IR','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('250','OBIS LX/LS FP (Fiber-Pigtailed)','Violet - Visible','','Diode    ','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('251','OBIS 375LX','Violet','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('252','OBIS405LX','Violet','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('253','OBIS 413LX','Visible','','Diode','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('254','OBIS 422LX','Visible','','Diode','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('255','OBIS 445LX','Visible','','Diode  ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('256','OBIS458LX','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('257','OBIS473LX','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('258','OBIS 488LX','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('259','OBIS 488LS','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('260','OBIS 505LX','Visible','','Diode  ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('261','OBIS 505LS','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('262','OBIS 514LX','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('263','OBIS 514LS','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('264','OBIS 520LX','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('265','OBIS 532LS','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('266','OBIS 552LS','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('267','OBIS 561LS','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('268','OBIS 594LS','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('269','OBIS 637LX','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('270','OBIS 640LX','Visible','','Diode  ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('271','OBIS 647LX','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('272','OBIS 660LX','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('273','OBIS 685LX','Visible','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('274','OBIS 730LX','Near IR','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('275','OBIS 752LX','Near IR','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('276','OBIS 785LX','Near IR','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('277','OBIS 808LX','Near IR','','Diode    ','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('278','OBIS 980LX','Near IR','','Diode','','','obis-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('279','OBIS FP 405LX','Violet','','Diode','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('280','OBIS FP 413LX','Visible','','Diode','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('281','OBIS FP 445LX','Visible','','Diode','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('282','OBIS FP 473LX','Visible','','Diode    ','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('283','OBIS FP 488LX','Visible','','Diode    ','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('284','OBIS FP 488LS','Visible','','Diode    ','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('285','OBIS FP 505LX','Visible','','Diode    ','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('286','OBIS FP 514LX','Visible','','Diode    ','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('287','OBIS FP 514LS','Visible','','Diode    ','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('288','OBIS FP 520LX','Visible','','Diode    ','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('289','OBIS FP 532LS','Visible','','Diode','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('290','OBIS FP 552LS','Visible','','Diode','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('291','OBIS FP 561LS','Visible','','Diode','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('292','OBIS FP 594LS','Visible','','Diode','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('293','OBIS FP 637LX','Visible','','Diode','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('294','OBIS FP 640LX','Visible','','Diode','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('295','OBIS FP 647LX','Visible','','Diode','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('296','OBIS FP 660LX','Visible','','Diode','','','obis-fp-fiber-pigtailed');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('310','OBIS LG Ultraviolet Laser','UV','','OPSL','','','obis-lg-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('311','OBIS LG 355-20','UV','','OPSL','','','obis-lg-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('312','OBIS LG 355-50','UV','','OPSL','','','obis-lg-lasers');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('2163','OBIS LX/LS Laser Box','','','','','','obis-laser-box');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('2164','OBIS LX/LS Scientific Remote','','','','','','obis-scientific-remote');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('2165','OBIS Laser Cable (0.3 meter)','','','','','','obis-laser-cable-0-3-meter');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('2166','OBIS Laser Cable (1 meter)','','','','','','obis-laser-cable-1-meter');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('2167','OBIS Laser Cable (3 meter)','','','','','','obis-laser-cable-3-meter');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('2168','OBIS LX/LS Single Laser Remote','','','','','','obis-single-laser-remote');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('2169','OBIS LX/LS Heat Sink','','','','','','obis-heat-sink');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('2170','OBIS LX/LS 6-Laser Remote','','','','','','obis-6-laser-remote');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('2171','OBIS LX/LS 2nd Emission Indicator','','','','','','obis-2nd-emission-indicator');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('2172','OBIS LX/LS Power Supply','','','','','','obis-power-supply');
INSERT INTO `magento_export` (`ID`,`Name`,`Wavelength`,`Operation_Mode`,`Technology`,`Mode`,`Pulse_Width`,`URL`) VALUE ('2173','OBIS Galaxy Laser Beam Combiner','','','','','','galaxy-laser-beam-combiner');
