INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1000','PowerMax-USB PM1K-36C Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1001','PowerMax-USB PM2 Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1002','PowerMax-USB PM3 Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1003','PowerMax-USB PM30 Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1004','PowerMax-USB PM3Q Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1005','PowerMax-USB PS10 Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1006','PowerMax-USB PS19 Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1007','PowerMax-USB PS19Q Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1008','PowerMax-USB UV/VIS Quantum Power Sensors','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1009','PowerMax-USB Wand UV/VIS Quantum Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1010','PowerMax-RS PM10-19C Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1011','PowerMax-RS PM150-19C Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1012','PowerMax-RS PM150-50C Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1013','PowerMax-RS PM30 Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1014','PowerMax-RS PM1K-36C Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1015','PowerMax-RS PS19Q Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1016','PowerMax-RS PM3K Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1017','S-1439','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1018','S-1516','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1019','S-1544','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1020','S-1545','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1021','S-1546','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1022','S-1547','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1023','S-1550','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1024','S-1551','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1025','Coherent Family Plan','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1026','ISO 17025:2005 Accreditation','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1027','Coherent C24 Program','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1028','Instrument Accessories','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1029','Soft carrying cases for FieldMate','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1030','Soft carrying cases for FieldMaxII, LabMax, and LabMax-Pro','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1031','Energy Sensor Damage Test Slides','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1032','EnergyMax Large Heat Sink','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1033','EnergyMax Medium Heat Sink','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1034','EnergyMax Small Heat Sink','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1035','EnergyMax Heat Sink Accessories','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1036','SMA Fiber Optic Connector','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1037','FC Fiber Optic Connector','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1038','FC Fiber Optic Connector','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1039','SMA Fiber Optic Connector','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1040','1.035-40M Adapter Ring','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1041','Fiber Optic Connector Adapters','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1042','AC Power Adapter','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1043','AC Power Adapter','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1044','Replacement AC Power Adapters','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1045','Thermal Smart Sensor Adapter','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1046','1000-1 Attentuator','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1047','COMPACT-AC','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1048','COMPACT-AC','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1049','COMPACT-AC','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1050','COMPACT-AC','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1051','COMPACT-AC','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1052','COMPACT-AC','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1053','COMPACT-AC Pkg','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1054','COMPACT-AC Pkg','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1055','COMPACT-AC Pkg','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1056','COMPACT-AC Pkg','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1057','COMPACT-AC Pkg','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1058','COMPACT-AC Pkg','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1059','DILAS-ILS COMPACT-AC Pkg','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1060','DILAS-ILS COMPACT-AC Pkg','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1061','DILAS-ILS COMPACT-AC Pkg','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1062','HighLight DL','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1063','HighLight DL2000HQ','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1064','HighLight DL6000HP (940 nm)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1065','HighLight DL6000HP (980 nm)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1066','Hstack','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1067','HStack EN 808nm 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1068','HStack EN 808nm 80W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1069','HStack EN 88xnm 880 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1070','HStack EN 88xnm 880 80W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1071','HStack EN 940nm 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1072','Vstack Family Page','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1073','VStack C3N SO10 1540nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1074','VStack C3N SO10 940nm 200W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1075','VStack C3N SO10 940nm 300W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1076','VStack C3N SO10 940nm 400W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1077','VStack_EN-Frameless_1064nm 40W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1078','VStack_EN-Frameless_1064nm 60W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1079','Water-Air Chiller (2500W) - for Water-Cooled Laser Systems up to 600W-1500W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1080','Water-Air Chiller (800W) - for Water-Cooled Laser Systems up to 500W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1081','Water-Water Chiller (800W) - for Water-Cooled Laser Systems up to 500W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1082','COMPACT-EVOLUTION','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1083','COMPACT-EVOLUTION 150W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1084','COMPACT-EVOLUTION 200W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1085','COMPACT-EVOLUTION 300W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1086','COMPACT-EVOLUTION 450W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1087','COMPACT-EVOLUTION 600W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1088','Mini DL System','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1089','Mini DL System','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1090','Mini DLSystem','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1091','COMPACT-EVOLUTION','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1092','COMPACT-EVOLUTION 1.2kW (1200)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1093','COMPACT-EVOLUTION 1kW (1000)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1094','COMPACT-EVOLUTION 800W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1095','BA','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1096','BA-1870-0700-SE','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1097','BA-1870-1000-SE','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1098','BA-1908-0700-SE','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1099','BA-1908-1000-SE','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1100','BA-1940-0700-SE','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1101','BA-1940-1000-SE','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1102','BA-2180-0500-SE','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1103','BA-2200-0500-SE','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1104','BA-2230-0500-SE','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1105','DirectBeam','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1106','DirectBeam EN-VH8 Stack','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1107','DirectBeam MMB 250W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1108','DirectBeam MMB 600W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1109','DirectBeam M1B 1550nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1110','DirectBeam M1B 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1111','DirectBeam M1L 250W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1112','DirectBeam M1L 250W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1113','DirectBeam M1L 250W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1114','DirectBeam M8L 600W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1115','MF','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1116','MF 105um, 793nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1117','MF 105um, 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1118','MF 105um, 976nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1119','MF 1064nm-400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1120','MF 1210nm, 400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1121','MF 1310nm, 400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1122','MF 1470nm, 200um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1123','MF 1470nm, 400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1124','MF 1530nm, 200um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1125','MF 1550nm, 400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1126','MF 1940nm, 400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1127','DILAS MF 638nm-400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1128','DILAS MF 675nm-400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1129','MF 793nm 200um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1130','MF 793nm 400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1131','MF 808nm, 200um, 30W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1132','MF 808nm, 200um, 40W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1133','MF 808nm, 400um, 100W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1134','MF 808nm, 400um, 30W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1135','MF 808nm, 400um, 40W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1136','MF 808nm, 400um, 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1137','MF 880nm, 400um, 30W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1138','MF 880nm, 400um, 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1139','MF 915nm, 200um, 30W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1140','MF 915nm, 400um, 30W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1141','MF 915nm, 400um, 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1142','MF 940nm, 200um, 30W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1143','MF 940nm, 400um, 100W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1144','MF 940nm, 400um, 30W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1145','MF 940nm, 400um, 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1146','MF 976nm, 200um, 30W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1147','MF 976nm, 200um, 40W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1148','MF 976nm-400um, 30W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1149','MF 976nm, 400um, 100W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1150','MF 976nm, 400um, 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1151','DILAS MF-NLW 793nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1152','DILAS MF-NLW 806.5nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1153','DILAS MF-NLW 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1154','DILAS MF-NLW 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1155','DILAS MF-NLW 879nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1156','DILAS MF-NLW 880nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1157','MF-NLW 976nm, 30W, 200/400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1158','MF-NLW 976nm, 40W, 200/400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1159','MF-NLW 981nm, 30W, 200/400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1160','MF-NLW 981nm, 40W, 200um/400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1161','MMF','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1162','MMF 3-Lambda-IS9, 1470nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1163','MMF 3-Lambda-IS9, 1520nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1164','MMF 3-Lambda-IS9, 1550nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1165','MMF 3-Lambda-IS9, Combined','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1166','MMF QCW IS28 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1167','MMF QCW IS28 940nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1168','MMF QCW IS39 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1169','MMF QCW IS39 940nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1170','DILAS MMF TBar IS21.11 120W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1171','DILAS MMF TBar IS21.11 135W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1172','DILAS MMF TBar IS21.11 200W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1173','DILAS MMF TBar IS21.16','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1174','DILAS MMF TBar IS45.1 600W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1175','DILAS MMF TBar IS45.1 600W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1176','DILAS MMF TBar IS46 300W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1177','MMF_TBar_IS58_240W_915nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1178','MMF_TBar-NLW_IS58_250W_976nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1179','MMF_TBar-NLW_270W_976nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1180','MMF_TBar_IS67.2-1200W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1181','MMF-IS10 200um 793nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1182','MMF-IS10 200um 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1183','MMF-IS10 200um 9xxnm 915nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1184','MMF-IS10 200um 9xxnm 940nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1185','MMF-IS10 200um 9xxnm 976nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1186','MMF-IS10 2-Lambda, 1470nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1187','MMF-IS10 2-Lambda, 980nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1188','MMF-IS10 400um 1470nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1189','MMF-IS10 400um 793nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1190','MMF-IS10 400um 808nm 240W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1191','MMF-IS10 400um 808nm 200W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1192','MMF-IS10 400um 880nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1193','MMF-IS10 400um 915nm 200W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1194','MMF-IS10 400um 915nm 240W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1195','MMF-IS10 400um 940nm 240W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1196','MMF-IS10 400um 940nm 200W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1197','MMF-IS10 400um 976nm 200W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1198','MMF-IS10 400um 976nm 240W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1199','MMF-IS10-NLW 976nm, 120W, 200um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1200','MMF-IS10-NLW 976nm, 180W, 200um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1201','MMF-IS10-NLW 981nm, 200W, 400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1202','MMF-IS10-QBH_200um_976nm.pdf','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1203','MMF-IS11 200um 793nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1204','MMF-IS11 200um 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1205','MMF-IS11 200um 9xxnm 915nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1206','MMF-IS11 200um 9xxnm 940nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1207','MMF-IS11 200um 9xxnm 976nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1208','DILAS MMF-IS11 400um 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1209','MMF-IS11 400um 808nm 500W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1210','DILAS MMF-IS11 400um 880nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1211','MMF-IS11 400um 9xxnm 915nm 300W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1212','MMF-IS11 400um 9xxnm 915nm 400W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1213','MMF-IS11 400um 9xxnm 915nm 500W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1214','MMF-IS11 400um 9xxnm 940nm 300W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1215','MMF-IS11 400um 9xxnm 976nm 300W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1216','MMF-IS11 400um 9xxnm 940nm 400W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1217','MMF-IS11 400um 9xxnm 976nm 400W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1218','MMF-IS11 400um 9xxnm 940nm 500W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1219','MMF-IS11 400um 9xxnm 976nm 500W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1220','MMF-IS11 600um 1940nm, 30W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1221','MMF-IS11-NLW 975.7nm, 400W, 400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1222','MMF-IS11-NLW 976nm, 240W, 200um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1223','MMF-IS11-NLW 976nm, 300W, 400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1224','MMF-IS11-NLW 976nm, 400W, 400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1225','MMF-IS11-NLW 979.5nm, 400W, 400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1226','MMF-IS30.4_400um_980+1470nm (1470nm)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1227','MMF-IS30.4_400um_980+1470nm (980nm)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1228','MMF-IS30 200um 793nm 60W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1229','MMF-IS30 200um 808nm 70W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1230','DILAS MMF-IS30 200um 9xxnm 915nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1231','MMF-IS30 200um 9xxnm 940nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1232','MMF-IS30 200um 9xxnm 976nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1233','MMF-IS30 400um 1470nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1234','MMF-IS30 400um 1550nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1235','MMF-IS30 400um 793nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1236','MMF-IS30 400um 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1237','MMF-IS30 400um 880nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1238','MMF-IS30 400um 9xxnm 915nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1239','MMF-IS30 400um 9xxnm 940nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1240','MMF-IS30 400um 9xxnm 976nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1241','DILAS MMF-IS30-NLW 790nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1242','MMF-IS43_976nm-300W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1243','MMF-IS9 200-400um 9xxnm (940nm)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1244','MMF-IS9 200-400um 9xxnm (976nm)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1245','MMF-IS9 400um 9xxnm 915nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1246','MMF-IS9 200um 793nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1247','MMF-IS9 200um 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1248','MMF-IS9 400um 1210nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1249','MMF-IS9 400um 1470nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1250','MMF-IS9 400um 793nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1251','MMF-IS9 400um 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1252','MMF-IS9 400um 880nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1253','MMF-IS9 600um 1940nm, 12W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1254','MMF-IS9 600um 1940nm, 18W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1255','MMF-1kW','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1256','DILAS MMF-IS9-NLW 794.7nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1257','DILAS MMF-IS9-NLW 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1258','MMF-IS9-NLW 976nm, 100W, 400um','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1259','SB','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1260','SB 1064nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1261','SB 1210nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1262','SB 1310nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1263','DILAS SB 1470nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1264','SB 1470nm 80W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1265','SB 1550nm 20W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1266','SB 1550nm 70W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1267','SB 1940nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1268','SB 638nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1269','SB 675nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1270','SB 79xnm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1271','SB 79xnm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1272','SB 808nm 150W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1273','SB 808nm 200W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1274','SB 808nm 280W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1275','SB 808nm 40W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1276','SB 808nm 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1277','SB 808nm 60W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1278','SB 880nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1279','SB 88xnm 885nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1280','SB 915nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1281','SB 940nm 300W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1282','SB 940nm 60W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1283','SB 976nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1284','SE','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1285','SE Module','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1286','SE_Module_793nm_HS1-PM3','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1287','SE_Module_915nm-30W_PM3','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1288','SE_Module_976nm-30W_PM3','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1289','SE_Module-976nm-50W_HS2-PM5','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1290','SE_Module-976nm-40W_HS2-PM5','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1291','SE_Module-976nm-90W_HS2-PM10','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1292','SE_Module-976nm-80W_HS2-PM10','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1293','SE_Module-NLW_976nm-25W_HS1-PM3','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1294','SE_Module-NLW_976nm-30W_HS2-PM5','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1295','SE_Module-NLW_976nm-60W_HS2-PM10','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1296','SE_Multi-Module-405nm_2.4W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1297','SE_Multi-Module-450nm_3W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1298','SE Multi-Module-450nm 10W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1299','SE Multi-Module-450nm 25W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1300','SE_Multi-Module-520nm_2W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1301','SE_Multi-Module-638nm_2W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1302','TA','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1303','TA-0765-1000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1304','TA-0765-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1305','TA-0780-1000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1306','TA-0780-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1307','TA-0785-1000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1308','TA-0785-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1309','TA-0795-3000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1310','TA-0850-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1311','TA-0850-3000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1312','TA-0860-3000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1313','TA-0870-1500','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1314','TA-0870-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1315','TA-0890-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1316','TA-0890-3000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1317','TA-0920-1000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1318','TA-0920-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1319','TA-0950-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1320','TA-0976-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1321','TA-0976-3000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1322','TA-1010-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1323','TA-1060-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1324','TAL','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1325','TAL-0765-1000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1326','TAL-0765-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1327','TAL-0780-1000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1328','TAL-0780-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1329','TAL-0785-1000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1330','TAL-0785-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1331','TAL-0795-3000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1332','TAL-0800-0500','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1333','TAL-0850-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1334','TAL-0850-3000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1335','TAL-0860-3000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1336','TAL-0870-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1337','TAL-0890-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1338','TAL-0890-3000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1339','TAL-0920-1000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1340','TAL-0920-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1341','TAL-0950-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1342','TAL-0976-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1343','TAL-0976-3000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1344','TAL-1010-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1345','TAL-1060-2000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1346','Vstack','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1347','VStack C3N-VO51 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1348','VStack C3N-VO51 940nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1349','VStack C3N-VO68 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1350','VStack C3N-VO68 940nm 175W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1351','VStack EB 808nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1352','VStack EB 940nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1353','VStack EN-AuSn-Multi-B 9xxnm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1354','VStack EN-AuSn-SB 9xxnm 980','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1355','VStack EN-Frameless 808nm 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1356','VStack EN-Frameless 808nm 80W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1357','VStack EN-Frameless 808nm 150W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1358','VStack EN-Frameless 808nm 250W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1359','VStack EN-Frameless 88xnm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1360','VStack EN-Frameless 9xxnm 980nm 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1361','VStack EN-Frameless 9xxnm 980nm 80W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1362','VStack EN-SB 808nm 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1363','VStack EN-SB 808nm 80W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1364','VStack EN-SB 808nm 150W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1365','VStack EN-SB 808nm 250W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1366','VStack EN-SB 88xnm 880nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1367','VStack_EN-SB_9xxnm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1368','VStack_EN-SB_9xxnm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1369','VStack EY-DPAL 766nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1370','VStack EY-DPAL 780nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1371','VStack EY-DPAL 852nm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1372','VStack EY-Housed 808nm 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1373','VStack EY-Housed 808nm 80W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1374','VStack EY-Housed 808nm 150W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1375','VStack EY-Housed 808nm 250W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1376','VStack EY-Housed 88xnm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1377','VStack EY-Housed 9xxnm 50W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1378','VStack EY-Housed 9xxnm 80W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1379','VStack NN 808nm 100W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1380','VStack NN 808nm 150W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1381','VStack NN 808nm 250W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1382','VStack NN 9xxnm 980nm 100W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1383','VStack NN 9xxnm 980nm 150W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1384','VStack NN 9xxnm 980nm 300W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1385','VStack NY 808nm 100W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1386','VStack NY 808nm 150W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1387','VStack NY 808nm 250W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1388','VStack NY 9xxnm 980nm 100W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1389','VStack NY 9xxnm 980nm 150W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1390','VStack NY 9xxnm 980nm 300W','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1391','COMPACT-WC-Blue','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1392','COMPACT-WC-Blue','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1393','COMPACT-WC-Blue','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1394','DILAS Fibers','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1395','DILAS Fiber 200um Modestrip-SMA-SMA','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1396','DILAS Fiber 400um Modestrip-SMA-SMA','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1397','DILAS Fiber LC-ModestripSMASMA_200','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1398','DILAS PT-Q Fiber','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1399','DILAS PT-Q Fiber_1000','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1400','DILAS PT-Q Fiber_200','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1401','DILAS PT-Q Fiber_300','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1402','DILAS PT-Q Fiber_400','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1403','DILAS PT-Q Fiber_600','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1404','DILAS PT-Q Fiber_800','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1405','DILAS Fiber-HP-SMASMA','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1406','DILAS Fiber-HP-SMASMA_200','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1407','DILAS Fiber-HP-SMASMA_400','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1408','DILAS Fiber-HP-SMASMA_600','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1409','DILAS Fiber-HP-SMASMA_800','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1410','F-Theta Scanning Lenses','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1411','F-Theta Scanning Lenses 80mm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1412','F-Theta Scanning Lenses 163mm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1413','F-Theta Scanning Lenses 254mm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1414','F-Theta Scanning Lenses 300mm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1415','F-Theta Scanning Lenses 330mm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1416','F-Theta Scanning Lenses 400mm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1417','F-Theta Scanning Lenses 420mm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1418','F-Theta Scanning Lenses 635mm','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1419','Galvo Scanner: Galvo Driver','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1420','Galvo Scanner: Galvo PC','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1421','Line Focus Processing Head (PHFx-B0-O1)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1422','Collimation Unit - High Power (PHFx-A8/A9-W)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1423','Collimation Unit - High Power (PHFx-A8/A9-W)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1424','Collimation Unit - Low Power (PHFx-A8/A9)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1425','Collimation Unit - Low Power (PHFx-A8/A9)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1426','Collimation Unit - Low Power (PHFx-A8/A9)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1427','Collimation Unit - Low Power (PHFx-A8/A9)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1428','Galvo Scanner with Pyrometer (PHFx-C1-SG6)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1429','Galvo Scanner with Pyrometer (PHFx-C1-SG6)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1430','Radial Optics (PHFx-B0-03)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1431','Radial Optic with Pyrometer PHFx-C1-SD1/SD2','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1432','Galvo Scanner (PHFx-B0-G6/G7)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1433','Spot Imaging: Pyrometer/Camera Processing Head (PHFx-Cx-CS)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1434','Spot Imaging: Pyrometer/Camera Processing Head (PHFx-Cx-CS)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1435','Spot Imaging: Pyrometer/Camera Processing Head (PHFx-Cx-CS)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1436','Spot Imaging: Pyrometer/Camera Processing Head (PHFx-Cx-CS)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1437','Spot Imaging: Pyrometer/Camera Processing Head (PHFx-Cx-CS)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1438','Spot Imaging: Pyrometer/Camera Processing Head (PHFx-Cx-CS)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1439','Ring Focus Processing Head (PHFx-B0-O2)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1440','Processing Head (PHFx-B0)','DILAS');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1441','Processing Head (PHFx-B0)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1442','Processing Head (PHFx-B0)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1443','Processing Head (PHFx-B0)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1444','Processing Head (PHFx-B0)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1445','Processing Head (PHFx-B0)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1446','10W, 20W, 30W, 50W, 100W Fiber Lasers For Marking','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1447','10W Fiber Lasers For Marking','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1448','20W Fiber Lasers For Marking','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1449','30W Fiber Lasers For Marking','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1450','50W Fiber Lasers For Marking','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1451','100W Fiber Lasers For Marking','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1452','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1453','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1454','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1455','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1456','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1457','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1458','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1459','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1460','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1461','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1462','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1463','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1464','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1465','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1466','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1467','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1468','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1469','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1470','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1471','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1472','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1473','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1474','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1475','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1476','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1477','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1478','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1479','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1480','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1481','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1482','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1483','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1484','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1485','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1486','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1487','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1488','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1489','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1490','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1491','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1492','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1493','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1494','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1495','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1496','1064 30W Fiber Amplifiers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1497','1064 50W Fiber Amplifiers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1498','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1499','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
