INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1500','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1501','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1502','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1503','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1504','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1505','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1506','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1507','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1508','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1509','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1510','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1511','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1512','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1513','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1514','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1515','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1516','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1517','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1518','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1519','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1520','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1521','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1522','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1523','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1524','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1525','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1526','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1527','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1528','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1529','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1530','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1531','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1532','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1533','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1534','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1535','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1536','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1537','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1538','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1539','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1540','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1541','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1542','1064 30W Fiber Amplifiers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1543','1064 50W Fiber Amplifiers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1544','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1545','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1546','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1547','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1548','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1549','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1550','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1551','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1552','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1553','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1554','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1555','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1556','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1557','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1558','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1559','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1560','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1561','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1562','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1563','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1564','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1565','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1566','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1567','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1568','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1569','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1570','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1571','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1572','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1573','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1574','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1575','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1576','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1577','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1578','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1579','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1580','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1581','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1582','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1583','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1584','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1585','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1586','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1587','1064 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1588','1064 30W Fiber Amplifiers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1589','1064 50W Fiber Amplifiers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1590','1064 - 1083 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1591','1084 - 1100 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1592','1100 - 1110 nm Single Frequency, PM, Fiber Amplifiers (Gen. II)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1593','Beam Delivery Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1594','Gyroscope Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1595','Laser & Amplifier Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1596','Multimode Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1597','Polarization Maintaining Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1598','Fiber Optic Gyroscope (FOG) Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1599','Current Sensing Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1600','Geophysical Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1601','Acoustic & Micro-Seismic Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1602','Medical Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1603','Radiation Environment Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1604','Single-Mode Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1605','30/250 with 0.09 NA Matched Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1606','10/125 Erbium/Ytterbium-Doped Multimode Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1607','20/400 NuMATCH LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1608','Nufern 980 nm Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1609','Eye Safe 9/125 Thulium-Doped Single-Mode Single Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1610','NuBEAM 200 µm Core Beam Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1611','NuBEAM 400 µm Core Beam Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1612','Eye Safe 9/125 Thulium-Doped Single-Mode Single Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1613','NuBEAM 100 µm Core Beam Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1614','NuBEAM 1000 µm Core Beam Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1615','NuBEAM 50 µm Core Beam Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1616','NuBEAM 50 µm Core Beam Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1617','NuBEAM 50 µm Core Beam Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1618','NuBEAM 100 µm Core Beam Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1619','NuBEAM 200 µm Core Beam Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1620','NuBEAM 200 µm Core Beam Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1621','NuBEAM 300 µm Core Beam Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1622','CATV Amplifier 6/125 Er:Yb-Doped Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1623','10/125 Erbium/Ytterbium-Doped Multimode Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1624','10/125 Erbium/Ytterbium-Doped Multimode Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1625','Eye Safe 25P/400-HE Thulium-Doped PLMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1626','Eye Safe 25P/400 Thulium Doped LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1627','Eye Safe 25P/250 Thulium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1628','50 µm Multimode Radiation Resistant Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1629','62.5 µm Multimode Radiation Resistant Fiber with High Temperature Acrylate','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1630','100 µm Multimode Radiation Resistant Fiber with High Temperature Acrylate','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1631','50 µm Specialty Multimode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1632','62.5 µm Specialty Multimode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1633','100 µm Specialty Multimode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1634','1310/1550 nm Single-Mode Radiation Hardened Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1635','Single-Mode Bend Insensitive Fiber with High Temperature Acrylate','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1636','Single-Mode Bend Insensitive Radiation Hardened Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1637','PM 5/125 Neodymium-Doped Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1638','980/1060 nm Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1639','1310/1550 nm Reduced Clad and Bend Insensitive Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1640','1310/1550 nm Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1641','1310/1550 nm Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1642','1310/1550 nm Reduced Clad and Bend Insensitive Medium-NA Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1643','1310/1550 nm Bend Insensitive Medium-NA Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1644','1550 nm Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1645','1550 nm Reduced Clad Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1646','405 nm Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1647','460 nm Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1648','630 nm Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1649','780 nm Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1650','Nufern 980 nm Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1651','Nufern 980 nm Reduced Clad Medium-NA Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1652','980 nm Reduced Clad Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1653','980/1550 nm Coupler Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1654','Cladding Mode Free Photosensitive Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1655','Cladding Mode Free Photosensitive Single-Mode Fiber with Polyimide Coating','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1656','HP Cladding Mode Suppressed Photosensitive Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1657','Cladding Mode Suppressed Photosensitive Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1658','C-Band Erbium-Doped Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1659','C-Band Reduced Clad Erbium-Doped Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1660','L-Band Erbium-Doped Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1661','L-Band Erbium-Doped Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1662','L-Band Reduced Clad Erbium-Doped Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1663','Photosensitive Single-Mode Low-NA Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1664','Photosensitive Single-Mode Low-NA Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1665','Photosensitive Single-Mode Low-NA Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1666','Photosensitive Single-Mode Medium-NA Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1667','NuSENSOR 50/125 Graded Index Pure Silica Core Multimode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1668','10/125 Ytterbium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1669','20/400 Ytterbium-Doped LMA Double Clad PM Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1670','25/250 Ytterbium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1671','25/400 Ytterbium-Doped LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1672','20/400 Ytterbium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1673','High Absorption 30/250 Ytterbium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1674','30/400 Ytterbium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1675','12/130 Erbium/Ytterbium-Doped Multimode Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1676','105 Micron Core Power Delivery Fiber 12A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1677','105 Micron Core Power Delivery Fiber 15A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1678','105 Micron Core Power Delivery Fiber 22A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1679','200 Micron Core Power Delivery Fiber 12A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1680','200 Micron Core Power Delivery Fiber 22A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1681','200 Micron Core Power Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1682','400 Micron Core Power Delivery Fiber 12A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1683','400 Micron Core Power Delivery Fiber 22A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1684','400 Micron Core Power Delivery Fiber 22FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1685','Eye Safe 25P/400-HE Thulium-Doped PLMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1686','10/125 Ytterbium-Doped LMA Double Clad PM Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1687','25/250 Ytterbium-Doped LMA Double Clad PM Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1688','25/400 Ytterbium-Doped LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1689','High Absorption 30/250 Ytterbium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1690','30/400 Ytterbium-Doped LMA Double Clad PM Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1691','PM Erbium-Doped Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1692','12/130 Erbium/Ytterbium-Doped Multimode Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1693','CATV Amplifier 6/125 Er/Yb-Doped Double Clad PM Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1694','Pure Silica Core Polarization Maintaining Fiber for UV-VIS Wavelengths','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1695','Pure Silica Core Polarization Maintaining Fiber for UV-VIS Wavelengths','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1696','460 nm Pure Silica Core Polarization Maintaining Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1697','630 nm Pure Silica Core Polarization Maintaining Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1698','Eye Safe 10P/130-HE Thulium-Doped Single-Mode Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1699','5/130 Ytterbium-Doped PM Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1700','Polarization Maintaining 1300 nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1701','300 nm PM Gyroscope & Sensor Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1702','Polarization Maintaining 14XX nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1703','14xx nm Polarization Maintaining Low Loss Coupler Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1704','Polarization Maintaining 1550 nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1705','1550 nm PM Gyroscope & Sensor Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1706','EyeSafe Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1707','460 nm Polarization Maintaining Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1708','630 nm Pure Silica Core Polarization Maintaining Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1709','780 nm Polarization Maintaining Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1710','50 nm PM Gyroscope & Sensor Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1711','Polarization Maintaining 980 nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1712','980 nm Polarization Maintaining Low Loss Coupler Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1713','3/125 Ultra-High NA Select Cutoff Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1714','980 nm Photosensitive Polarization Maintaining Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1715','Photosensitive Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1716','Planar Waveguide Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1717','Pure Silica Core Visible Wavelength Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1718','Pure Silica Core Visible Wavelength Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1719','1550 nm Single-Mode Double Clad Coupler Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1720','SM-ESF-7/125','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1721','CATV Amplifier 6/125 Er:Yb-Doped Double Clad SM Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1722','5/130 Ytterbium-Doped Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1723','7/210 Ytterbium-Doped Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1724','EyeSafe Delivery Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1725','Ultra-High NA Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1726','Ultra-High NA Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1727','Ultra-High NA Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1728','Pure Silica Core Visible Wavelength Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1729','Ultra-High NA Select Cutoff Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1730','Cladding Mode Offset Photosensitive Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1731','20/400 NuMATCH LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1732','20/400 NuMATCH LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1733','Eye Safe 10P/130-HE Thulium-Doped Single-Mode Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1734','30/250 Ytterbium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1735','30/250 Ytterbium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1736','C-Band & L-Band Photosensitive Erbium-Doped Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1737','LMA Ytterbium Doped DC Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1738','PM LMA Ytterbium Doped DC Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1739','10/400 Ytterbium-Doped MA Double Clad Fibers)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1740','10/400 Ytterbium-Doped MA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1741','17/200 Erbium/Ytterbium Co-Doped Double-Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1742','30/250 Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1743','30/250 Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1744','20/130 Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1745','20/130 Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1746','15/130 Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1747','15/130 Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1748','10/400 Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1749','10/400 Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1750','EyeSafe 25 Micron Core Holmium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1751','EyeSafe 40 Micron Core Holmium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1752','20/130 Ytterbium-Doped LMA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1753','20/130 Ytterbium-Doped LMA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1754','10/130 Precision Matched Active LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1755','10/130 Precision Matched Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1756','25/250 Precision Matched Active LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1757','25/250 Precision Matched Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1758','25/250 Precision Matched Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1759','10/125 Precision Matched Active LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1760','25/250 Precision Matched Active LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1761','25/250 Precision Matched Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1762','5/130 Passive Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1763','5/130 Passive Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1764','1550-nm Single-Mode Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1765','1550-nm Single-Mode Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1766','10/125 Precision Matched Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1767','20/400 Precision Matched Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1768','30/400 Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1769','30/400 Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1770','25/400 Precision Matched Active LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1771','25/400 Precision Matched Active LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1772','20/130 Precision Matched Active LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1773','25/400 Precision Matched Passive LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1774','25/400 Precision Matched Passive LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1775','25/300 Erbium/Ytterbium Co-doped LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1776','25/300 Erbium/Ytterbium Co-doped LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1777','25/300 Passive LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1778','25/300 Passive LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1779','Polarization Maintaining 980 nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1780','Polarization Maintaining 1300 nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1781','Polarization Maintaining 14XX nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1782','Polarization Maintaining 1550 nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1783','Elliptical-clad Polarization Maintaining Gyroscope & Sensor Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1784','EyeSafe 10 Micron Core Holmium-Doped SM Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1785','6/125 Precision Matched Passive Single-Mode 1550-nm Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1786','6/125 Precision Matched Passive Single-Mode 1550-nm Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1787','12/130 Precision Matched Passive 1550 nm Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1788','12/130 Precision Matched Passive 1550 nm Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1789','High Absorption 30/250 Precision Matched Ytterbium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1790','15/130 Precision Matched Ytterbium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1791','Eye Safe 25P/250 Thulium-Doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1792','Eye Safe 5/125 Thulium-Doped Single-Mode Single Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1793','EyeSafe 40 Micron Core Holmium-Doped LMA All-Glass Double-Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1794','Single-Mode Bend Insensitive Radiation Hardened Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1795','Elliptical-clad Polarization Maintaining Gyroscope & Sensor Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1796','10/130 Polarization Maintaining Precision Matched Passive 2000-nm Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1797','1060 nm Dispersion Controlled Select Cutoff Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1798','20/400 Ultra Matched+ Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1799','30/250 Ultra Matched+ Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1800','780 nm Dispersion Controlled Select Cutoff Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1801','20/400 Ultra Matched+ Yb-doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1802','High Absorption 30/250 Ultra Matched+ Yb-doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1803','High Absorption 10/125 Ytterbium-Doped PLMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1804','25/400 Ultra Matched+ Yb-doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1805','25/400 Ultra Matched+ Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1806','1060 nm Polarization Maintaining Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1807','1060 nm Polarization Maintaining Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1808','S1310-P','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1809','8/130 Precision Matched Passive SM Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1810','8/130 Precision Matched Passive SM Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1811','10/125 Precision Matched Passive LMA Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1812','10/125 Precision Matched Passive LMA Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1813','10/200 Precision Matched Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1814','850 nm PM Gyroscope & Sensor Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1815','1300 nm PM Gyroscope & Sensor Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1816','1550 nm PM Gyroscope & Sensor Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1817','850 nm PM Gyroscope & Sensor Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1818','1300 nm PM Gyroscope & Sensor Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1819','1550 nm PM Gyroscope & Sensor Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1820','8/130 NuGEN9 Precision Matched Active SM Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1821','10/125 NuGEN9 Precision Matched Active LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1822','10/200 NuGEN9 Precision Matched Active LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1823','30/250 NuGEN9 Precision Matched Active LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1824','20/400 NuGEN9 Precision Matched Active LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1825','1060 nm Dispersion Controlled Select Cutoff Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1826','Polarization Maintaining 980 nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1827','Polarization Maintaining 980 nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1828','Polarization Maintaining 1300 nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1829','Polarization Maintaining 1300 nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1830','Polarization Maintaining 14XX nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1831','Polarization Maintaining 14XX nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1832','Polarization Maintaining 1550 nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1833','Polarization Maintaining 1550 nm Telecommunication Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1834','Pure Silica Core Polarization Maintaining Fiber for UV-VIS Wavelengths','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1835','NuSENSOR 50/125 Graded Index Pure Silica Core Multimode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1836','NuSENSOR 1310/1550 nm Pure Silica Core Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1837','NuSENSOR 50/125 Graded Index Multimode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1838','NuSENSOR 1550 nm Bend Insensitive Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1839','20/400 Ultra Matched Yb-doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1840','25/400 Ultra Matched+ Yb-doped LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1841','10/125 Ytterbium-Doped Single-Mode Single Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1842','10/125 Ytterbium-Doped Single-Mode Single Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1843','NuSENSOR 1310/1550 nm Pure Silica Core Single-Mode Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1844','NuSENSOR 1310/1550 nm Pure Silica Core Single-Mode Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1845','XLMA Ytterbium-Doped Triple Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1846','XLMA-Ytterbium-Doped Triple Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1847','Erbium/Ytterbium-Doped LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1848','NuSENSOR 50/125 Graded Index Pure Silica Core Multimode Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1849','NuSENSOR 50/125 Graded Index Pure Silica Core Multimode Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1850','NuSENSOR 50/125 Graded Index Multimode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1851','105/106.5 Micron Core Power Delivery Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1852','135 Micron Core Power Delivery Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1853','NuSENSOR 1550 nm Bend-Insensitive Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1854','NuSENSOR 1550 nm Bend-Insensitive Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1855','NuSENSOR 1550 nm Bend-Insensitive Single-Mode Fiber)','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1856','NuSENSOR 1550 nm Bend-Insensitive Single-Mode Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1857','100 Micron Core Beam Delivery Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1858','Ytterbium-Doped Single-Mode Single Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1859','Ytterbium-Doped Single-Mode Single Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1860','Ytterbium-Doped Single-Mode Single Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1861','Ytterbium-Doped Single-Mode Single Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1862','Low Index Specialty Multimode Beam Delivery Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1863','Low Index Specialty Multimode Beam Delivery Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1864','10/130 Single Mode Precision Matched Passive 2000-nm Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1865','25/400 with 0.09 NA Matched Passive LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1866','25/250 with 0.09 NA Matched Passive LMA Double Clad Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1867','Eye Safe 10P/130 Thulium-Doped Single-Mode Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1868','Eye Safe 25P/250 Thulium-Doped LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1869','Eye Safe 25P/400 Thulium Doped LMA Double Clad Fibers','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1870','Dispersion tailored fibers for 2 um pulsed applications','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1871','Dispersion tailored fibers for 2 um pulsed applications','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1872','62.5/125-GI-PI','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1873','62.5/125-G-A-200K','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1874','50/125-GI-A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1875','MM-S200/240-22A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1876','PS-GDF-10/400','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1877','1550-GDF','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1878','MM-GSF-20/125-11A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1879','MM-GDF-20/200-11FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1880','MM-200-FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1881','1060-GDF','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1882','980-GDF','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1883','PM780-BK-S-BN','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1884','PM1060-GDF','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1885','PM630-BK-S-BN','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1886','SM-SDF-6/130','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1887','MM-250-FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1888','MM-GDF-25/250-11FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1889','MM-400-FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1890','MM-S105/125-22A-HP','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1891','PM085 LNA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1892','PM1550-BL-LTH','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1893','PM1300-BL-LTH','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1894','PM085 LNA-FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1895','PM1550-GDF','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1896','PM14XXC-A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1897','SM-GDF-8/130','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1898','780-XP','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1899','PM780C-A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1900','PM075 LNA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1901','PM075 LNA-FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1902','PM095-1550 LNA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1903','PM095-1550 LNA-FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1904','LMA-GDF-15/250','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1905','SM-GSF-8/125','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1906','SM-GDF-8/125','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1907','MM-125-FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1908','SM-GDF-10/125','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1909','SM-GSF-10/125','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1910','PS-GDF-8/130','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1911','SM780','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1912','SM-SDF-12/130','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1913','MM-GSF-20/125-30A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1914','PM1550C-80','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1915','MM-300-FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1916','LMA-GDF-25/400-08FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1917','PM530','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1918','MM-S220/242-22A-HP','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1919','LMA-GDF-20/400-10FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1920','PLMA-GDF-25/400-10FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1921','460-HP-HTT-BL','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1922','MM-GSF-20/125-10A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1923','MM-S105/125-22A-HYT','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1924','PM1550C2-80','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1925','MM-S105/125-22A-HIOH','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1926','PM630-HP-BK-S-BN','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1927','MM-S105/125-15A-XP','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1928','MM-S200/220-15A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1929','MM-GDF-25/400-11FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1930','LMA-GDF-20/400-XP','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1931','MM-S220/242-22A-XP','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1932','PM460C-HP','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1933','CMS8','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1934','PM-S460-HYT-VIOLET','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1935','PM630-HYT-BL-2mm PVDF','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1936','MM-S105/125-15A-HTA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1937','PM-DSF-12/130','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1938','LMA-GSF-15/123','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1939','PM-GDF-10/130-15FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1940','SM-GDF-10/125-15FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1941','PWG-80','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1942','PM-S460-PS','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1943','SM-GDF-10/125-V2','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1944','LMA-GDF-20/395','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1945','R1550-PI','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1946','MM-S200/220-22FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1947','PS-GDF-40/250-07FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1948','S-GDF-20/125-07FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1949','PS-GDF-25/625-08FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1950','CMS9','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1951','GI-50/125-20-HTA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1952','PM-GDF-43/400','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1953','PM-S460-XP','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1954','MM-GDF-25/250-11FA-XP','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1955','MM-S105/124-22A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1956','SM-GDF-10/130-15FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1957','CMS-10','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1958','980C-MC','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1959','PS-GDF-10/127-15FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1960','MM-S200/240-22FA-XP','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1961','SM-GDF-10/127-15FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1962','780-HP-YHYT','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1963','EDFC-980-HA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1964','PS-PLMA-GSF-10/125','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1965','LMA-GDF-23/250-09FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1966','PM980-LC','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1967','MM-S200/220-15A-HP','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1968','MM-S106.5/125-22A-HTA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1969','CMS-11','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1970','PM-S405-HNA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1971','MM-S105/125-15A-LTH','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1972','MM-S200/240-22S-TN','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1973','PM-S405-EXT','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1974','MM-S200/220-22FA-C','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1975','PM1950-BL-LTH','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1976','50/125-GR-A-02','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1977','PM060 LNA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1978','PS-PM-GDF-20/400','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1979','MM-125-A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1980','MM-350-FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1981','SM-GSF-8/130','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1982','GF1B-PI','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1983','PS-GDF-20/400-10FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1984','MM-S200/220-22HTA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1985','PM-CMS7','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1986','780-HP-HYT-BK','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1987','MM-S105/125-22A-HTA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1988','EDFL-1250','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1989','GI-100/330-29FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1990','MM-S105/125-12A-HP','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1991','PM-S405-XP-BK-S-BLN','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1992','S460-PI','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1993','MM-EYDF-60/600','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1994','CMS-11-HP','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1995','LMA-GDF-20/250-07FA','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1996','MM-S222/266-22S-TN','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1997','MM-S227/272-22S-TN','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1998','MM-S232/278-22S-TN','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1999','MM-S237/284-22S-TN','Nufern');
