INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2000','SM-EYDF-6/125','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2001','LMA-TDF-23P/250-09FA-V2','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2002','MM-S105/125-22A-V3','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2003','MM-S400/440/660-S','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2004','MM-S200/230/660-S','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2005','MM-DSF-12/125','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2006','MM-400-A Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2007','1550-A Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2008','MM-S105/125-22A-LTH Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2009','PM1550C-80-V3 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2010','PM1550-BK-S-BN Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2011','S405-XP-PVC-BL-3mm Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2012','460-HP-PVC-BL-3mm Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2013','630-HP-PVC-RD-3mm Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2014','1060-XP-PVC-RD-3mm Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2015','MM-S200/240-22HTA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2016','PM-S405-XP-BK-S-BKN Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2017','PS-GDF-10/125-15FA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2018','LMA-GDF-48/400 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2019','LMA-YDF-20/130-HI-8 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2020','MM-62-FA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2021','MM-400-HIOH-FA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2022','MM-250-HIOH-FA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2023','MM-130-HIOH-FA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2024','MM-S107/117-22FA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2025','MM-S200/220-22S Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2026','SM-GDF-10/125-HP Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2027','MM-S105/125-15A-200K Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2028','62.5/125-G-A Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2029','MM-S105/125-22S Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2030','MM-S200/240-22P Optical Fiberr','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2031','MM-S105/125-15P Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2032','1060-XP-LTH-YL-3mm Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2033','1550B-HP-LTH-YL-3mm Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2034','PM1550G-80-200K Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2035','MM-S200/240-15HTA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2036','PLMA-YDF-10/125-HA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2037','PS-GDF-15/250 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2038','MM-S113/125-22HTA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2039','PM1300-RD-LTH Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2040','PM-TDF-10/130-V1 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2041','MM-S50/70/360-22FA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2042','MM-S50/70/480-22S-TN Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2043','PM850G-45-ECG Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2044','MM-S220/242-22FA-XP Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2045','SM-9/105/125-20A-LC Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2046','LMA-GSF-30/250-07A Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2047','MM-YDF-7/128 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2048','LMA-YDF-10/125-HI Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2049','MM-600-FA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2050','LMA-YDF-14/360 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2051','MM-S106.5/125-15FA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2052','60-HP-80-BK Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2053','460-HP-80 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2054','MM-EYDF-10/125 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2055','MM-EYDF-8/125 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2056','MM-80-A','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2057','MM-S135/155-22FA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2058','MM-S206/223-22FA-C Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2059','PS-GDF-25/400-09FA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2060','PM14XXC-A V1 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2061','MM-400-FA-XP Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2062','MM-S231/246-22FA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2063','MM-S106.5/125-22FA Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2064','GR-62.5/125-27HTA-XP Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2065','CMS6 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2066','LMA-GDF-14/360 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2067','1310-GDF Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2068','S460-BK-HYT-YL Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2069','LMA-YDF-48/400E Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2070','PLMA-DSF-10/125 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2071','LMA-GDF-30/600 Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2072','UHNA7-4RIB-SWRBk Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2073','UHNA7-4RIB-BrGOB Optical Fiber','Nufern');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2074','HighLight FL-1000P','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2075','HighLight FL-ARM','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2076','HighLight FL-Series','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2077','HighLight FL3000C','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2078','HighLight FL10000','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2079','HighLight DD-Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2080','HighLight 10000D','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2081','HighLight 8000D','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2082','HighLight 4000D','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2083','CO2 Slab Laser','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2084','StarShape HP','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2086','DC Series','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2087','PowerLine F','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2088','PowerLine F 20','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2089','PowerLine F 20 Varia','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2090','PowerLine F 30','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2091','PowerLine F 50','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2092','PowerLine F 100','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2093','PowerLine E','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2094','PowerLine L','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2095','PowerLine L 100 SHG','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2096','PowerLine L 400','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2097','PowerLine Prime','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2098','PowerLine Prime 12','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2099','PowerLine Prime 15','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2100','PowerLine Pico','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2101','PowerLine Pico 10-1064','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2102','PowerLine Pico 10-532','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2103','PowerLine Pico 50-1064','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2104','PowerLine Pico 50-532','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2105','StarFiber 100-600','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2106','StarFiber 100','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2107','StarFiber 200','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2108','StarFiber 400','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2109','StarFiber 600','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2110','StarFiber OEM 100','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2111','StarFiber OEM 200','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2112','StarFemto FX','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2113','StarFemto FX 1030','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2114','StarFemto FX 515','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2115','StarFemto FX 343','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2116','StarPulse','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2117','StarPulse 40','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2118','StarPulse 90','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2119','StarPulse 150','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2120','StarShape','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2121','SSH 100 C/P','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2122','SSH 150 C/P','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2123','SSH 250 C/P','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2124','Incoupling Optics','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2125','Fiber-to-Fiber Optic Switch','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2126','Fiber-to-Fiber Optic Switch Air-cooled','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2127','Fiber-to-Fiber Coupler','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2128','Fiber-to-Fiber Coupler Air-cooled','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2129','Fiber Coupling Unit','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2130','Fiber Optic Cables','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2131','QBH Fiber Optic Cable','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2132','RQB Fiber Optic Cable','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2133','QD Fiber Optic Cable','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2134','QCR Fiber Optic Cable','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2135','QCS Fiber Optic Cable','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2136','SMAQ Fiber Optic Cable','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2137','External Optics','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2138','Collimating Units','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2139','Focusing Unit','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2140','Beam Bender Cube','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2141','Collimating Units','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2142','Focusing Units','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2143','Focusing Unit Z-adjustable','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2144','Beam Bender Cube','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2145','Twin Spot Optics','Optoskand');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2146','Tinsley Custom Optics','Tinsley');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2147','Tinsley Custom Optics - Glass','Tinsley');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2148','Tinsley Custom Optics - Metals','Tinsley');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2149','Tinsley Custom Optics - SiC','Tinsley');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2150','UW1200','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2151','UW180','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2152','UW150RT','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2153','Select','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2154','Select','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2155','Select with SweetSpot','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2156','Select Fiber','Rofin');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2157','EasyMark','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2158','EasyMark 10E','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2159','EasyMark F20','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2160','EasyMark F30','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2161','EasyMark F50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2162','Production Automation Options for META','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2163','OBIS LX/LS Laser Box','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2164','OBIS LX/LS Scientific Remote','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2165','OBIS Laser Cable (0.3 meter)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2166','OBIS Laser Cable (1 meter)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2167','OBIS Laser Cable (3 meter)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2168','OBIS LX/LS Single Laser Remote','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2169','OBIS LX/LS Heat Sink','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2170','OBIS LX/LS 6-Laser Remote','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2171','OBIS LX/LS 2nd Emission Indicator','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2172','OBIS LX/LS Power Supply','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2173','OBIS Galaxy Laser Beam Combiner','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2174','Sapphire LP/SF Driver Unit','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2175','Custom OEM Subsystems','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2176','Custom and OEM Diode Laser Products','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2177','Micro Channel Cooled Package (MCCP)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2178','COMPex','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2179','COMPex 50 FBG','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2180','COMPex 50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2181','COMPex 102','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2182','COMPex 110','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2183','COMPex 201','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2184','COMPex 205','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2185','StingRay Developers Kit','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2186','FieldMaxII Rechargeable Battery Pack','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2187','Pulse Compressors','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2188','Synchrolock-AP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2189','Synchrolock-AP Mira (fs)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2190','Synchrolock-AP Mira (ps)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2191','Synchrolock-AP Mira','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2192','Vitara-CEP Stabilizer','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2193','Chameleon PreComp Accessory','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2194','Chameleon VUE Harmonics Accessory','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2195','Chameleon VUE SHG','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2196','Chameleon VUE THG','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2197','Hidra - 10 Hz High Energy Ultrafast Amplifiers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2198','Hidra -25','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2199','Hidra-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2200','Hidra-100','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2201','Hidra Hybrid','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2202','CEP for Legend Elite Amplifiers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2203','Single-Shot Autocorrelator (SSA)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2204','Polarization Maintaining Fiber-PMF-488-B1','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2205','Polarization Maintaining Fiber-PMF-1550-B2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2206','Polarization Maintaining Fiber-PMF-633-B1','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2207','Polarization Maintaining Fiber-PMF-RC-1300-B1','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2208','Polarization Maintaining Fiber-PMF-RC-1300-B2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2209','Polarization Maintaining Fiber-PMF-RC-1550-B1','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2210','Polarization Maintaining Fiber-PMF-RC-820-B1','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2211','BIF-1310-L2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2212','BIF-RC-1310-L2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2213','BIF-780-L2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2214','BIF-RC-780-L2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2215','BIF-1550-L2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2216','BIF-RC-1550-L2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2217','Near UV-VIS Silica Core Fiber-NUV-320-K1','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2218','Select Cut-Off Single-Mode Fiber-SCSM-1060-HP1','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2219','Select Cut-Off Single-Mode Fiber-SCSM-450-HP1','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2220','Select Cut-Off and Standard Single-Mode Fiber-SCSM-633-HP1','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2221','CUBE Accessories','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2222','Visible Mini Diode Laser Modules','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2223','VLM2-3L, 2mW, 670nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2224','VMB2.3-4L, 4mW, 635nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2225','VHK2.3-1L, 1mW, 635nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2226','VHK2.1L. 1mW, 670nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2227','VLM2-8L, 7.5mW, 670nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2228','VLM3.5-2, 1.6mW, 650nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2229','VLM3-1L, 1mW, 670nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2230','VLM3-5L, 5mW, 670nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2231','UV Optical Components','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2232','90° Elbows','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2233','Interference Filters','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2234','Mounting Brackets','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2235','Power Supplies','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2236','Safety Key Box with Remote Interlock','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2237','Universal Voltage Adapter','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2238','Second Harmonic Bandwidth Compressor (SHBC)/TOPAS-400','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2239','StingRay Accessories','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2240','StingRay Power Supply - Laser','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2241','StingRay Multi-Axis Mount','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2242','StingRay Heat Sink Mount','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2243','StingRay Mount Adapter Plate','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2244','StingRay CDRH Safety Controller Kit','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2245','StingRay Power Supply - Controller','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2246','StingRay 12-Pin Hirose Connector','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2247','Coherent Connect Software','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2248','CUBE 660-60C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2249','CUBE 685-40C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2250','CUBE 730-30C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2251','DIAMOND FLQ-Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2252','Diamond FLQ-1064-0010-YZ','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2253','Diamond FLQ-1064-0020-YZ','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2254','Diamond FLQ-1064-0030-YZ','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2255','Diamond FLQ-1064-0050-YZ','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2256','Diamond FLQ-1064-0100-YZ','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2257','Ultra Low-Noise Laser Diode Modules','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2258','ULN 635 nm 5 mW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2259','Intermediate Optics','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2260','Process Adapters & Holders','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2261','DIAMOND FLC Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2262','DIAMOND FLC-100','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2263','DIAMOND FLC-200','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2264','Performance Family','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2265','Performance Family - Classic','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2266','Performance Family - SweetSpot','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2267','MPS Compact','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2268','EasyJewel','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2269','EasyJewel 10E','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2270','EasyJewel F20','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2271','EasyJewel F30','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2272','EasyJewel F50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2273','StarCut Tube','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2274','StarCut Tube SL','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2275','MPS Flexible','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2276','MPS Rotary','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2277','MPS Advanced','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2278','Desktop','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2279','LME','');
