INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('500','Staccato','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('501','SUPER RAPID-HE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('502','SUPER RAPID-HE 1064','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('503','SUPER RAPID-HE 532','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('504','SUPER RAPID-HE 355','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('505','VYPER','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('506','TwinVYPER','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('507','VYPER','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('508','Paladin Advanced 355','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('509','Paladin Advanced 355-10000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('510','Paladin Advanced 355-16000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('511','Paladin Advanced 355-24000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('512','Paladin Advanced 355-8000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('513','Paladin Compact 355','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('514','Paladin Compact 355-2000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('515','Paladin Compact 355-4000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('516','Paladin Advanced 532','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('517','Paladin Advanced 532-20000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('518','Chameleon Compact OPO Family','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('519','Chameleon Compact OPO-Vis (OPO Bypass Mode - Chameleon Laser)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('520','Chameleon Compact OPO-Vis (OPO Bypass Mode - Chameleon SHG)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('521','Chameleon Compact OPO-Vis (OPO Operation - Chameleon)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('522','Chameleon Compact OPO-Vis (OPO Operation - OPO)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('523','Chameleon Compact OPO-Vis (OPO Operation - Chameleon SHG)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('524','Chameleon Compact OPO-Vis (OPO Operation - OPO SHG)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('525','Chameleon Discovery','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('526','Chameleon Compact OPO (Pumped by Chameleon Ultra II)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('527','Chameleon Compact OPO (Pumped by Chameleon Vision II)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('528','Chameleon MPX (Pumped by Chameleon Vision II)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('529','Chameleon MPX (Pumped by Chameleon Ultra II)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('530','Chameleon Ultra','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('531','Chameleon Ultra','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('532','Chameleon Ultra I','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('533','Chameleon Ultra II','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('534','Chameleon Vision','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('535','Chameleon Vision I','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('536','Chameleon Vision II','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('537','Chameleon Vision S','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('538','DFG 9800/9850','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('539','DFG 9800','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('540','DFG 9850','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('541','Legend Elite HE+','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('542','Legend Elite USX/USP Duo -HE+','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('543','Legend Elite F/P Duo -HE+','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('544','Legend Elite USX/USP HE+','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('545','Legend Elite F/P HE+','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('546','Legend Elite Cryo PA','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('547','Libra','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('548','Libra','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('549','Libra-HE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('550','Libra-HE+','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('551','Mira 900','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('552','Mira Optima 900-F','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('553','Mira Optima 900-P','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('554','Mira Optima 900-D','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('555','Mira Optima 900-S','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('556','Mira-HP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('557','Mira HP-F','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('558','Mira HP-P','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('559','Mira HP-D','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('560','Mira-OPO','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('561','Mira OPO-X (IR-femtosecond)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('562','Mira OPO-X (IR-picosecond)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('563','Mira OPO-X (Vis + IR - femtosecond)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('564','Mira OPO-X (Vis + IR - picosecond)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('565','OPerA Solo kHz OPA','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('566','OPerA Solo','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('567','OPerA Solo (SH Package)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('568','OPerA Solo (SF Package)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('569','OPerA Solo (FH Package)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('570','OPerA Solo (SHSF Package)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('571','OPerA Solo (NDFG Package)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('572','RegA','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('573','RegA 9000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('574','RegA 9000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('575','RegA 9040','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('576','RegA 9050','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('577','TOPAS-Prime kHz OPA','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('578','TOPAS-Prime','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('579','TOPAS-Prime-VIS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('580','TOPAS-Prime-BLUE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('581','TOPAS-Prime-UV1','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('582','TOPAS-Prime-UV2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('583','TOPAS-Prime-NDFG1/2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('584','Vitara','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('585','Vitara-S','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('586','Vitara-T','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('587','Vitara-T-HP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('588','Vitara-UBB','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('589','DF Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('590','PRC Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('591','CH Series High Power Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('592','FH Series High Power Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('593','FH 7000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('594','FH 8000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('595','PLS Series Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('596','PLS 2500','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('597','PLS 3000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('598','PLS 3300','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('599','PLS 4000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('600','GL Series Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('601','GL 1000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('602','GL 1500','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('603','GL 2000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('604','Corelase','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('605','H-LASE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('606','H-LASE 1.5 kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('607','H-LASE 2kW SM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('608','H-LASE 2kW MM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('609','H-LASE 4kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('610','H-LASE 6kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('611','H-LASE 8kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('612','X-LASE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('613','X-LASE 24-6','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('614','X-LASE CoreScriber','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('615','O-LASE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('616','O-LASE 1500','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('617','O-LASE 2000 SM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('618','O-LASE 2000 MM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('619','O-LASE 4000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('620','O-LASE 6000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('621','O-LASE 8000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('622','Lasag','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('623','PWS-Mini','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('624','QFS with FLBK SC','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('625','QFS with FLBK SC (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('626','SLS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('627','SLS-CL8','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('628','SLS-CL16','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('629','SLS-CL60','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('630','SLS-CL60HP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('631','NA','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('632','NA 100 N','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('633','NA 200 N','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('634','NA 302 N','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('635','NA 502 N','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('636','KLS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('637','KLS-040 FC','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('638','KLS-046','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('639','KLS-102','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('640','KLS-302','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('641','KLS-306','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('642','KLS-502','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('643','FLS CL','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('644','FLS 542CL','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('645','FLS 542CL-HP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('646','FLS 542CL','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('647','FLS 542CL-HP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('648','FLS A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('649','FLS 352A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('650','FLS 352A-HB','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('651','FLS 652A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('652','QFS 50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('653','QFS 50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('654','QFS 50 (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('655','Lee Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('656','LDP-100TQG-DP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('657','LDP-100TQ','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('658','LDP-100MQG','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('659','LDP-100MQ','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('660','LDP-200MQU-HP-Dual','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('661','LDP-200MQU-HP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('662','LDP-100MQU','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('663','Monaco','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('664','Monaco 1035-40','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('665','Monaco 1035-80','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('666','Monaco 517-20','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('667','Monaco 517-30','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('668','FLARE NX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('669','FLARE NX 1030-1.0-2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('670','FLARE NX 515-0.6-2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('671','FLARE NX 343-0.2-2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('672','Revolution','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('673','REVOLUTION-20','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('674','REVOLUTION-25','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('675','REVOLUTION-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('676','REVOLUTION-65','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('677','REVOLUTION-80','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('678','Mephisto/Mephisto S','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('679','Mephisto','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('680','Mephisto S','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('681','Mephisto MOPA','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('682','Mephisto MOPA','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('683','Prometheus','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('684','Prometheus','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('685','HELIOS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('686','HELIOS 1064-2.5-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('687','HELIOS 1064-5-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('688','HELIOS 1064-6-125','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('689','HELIOS 532-1-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('690','HELIOS 532-1.5-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('691','HELIOS 532-3-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('692','HELIOS 532-4-125','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('693','LAMBDA SX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('694','Lambda SX K300','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('695','Lambda SX C300','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('696','Lambda SX C600','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('697','Lambda SX E300','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('698','Lambda SX E500','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('699','GeoLasHD','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('700','VarioLas Family','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('701','VarioLas ECO','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('702','VarioLas PRO','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('703','VarioLas SWEEP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('704','UVblade','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('705','UVblade 250','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('706','UVblade 380','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('707','UVblade 465','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('708','UVblade 750','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('709','LineBeam','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('710','LineBeam Series 3 - LB250','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('711','LineBeam Series 3 - LB275','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('712','LineBeam Series 3 - LB370','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('713','LineBeam Series 3 - LB380','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('714','LineBeam 465','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('715','LineBeam 750','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('716','LineBeam 1000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('717','LineBeam 1300','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('718','INNOVA ICE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('719','Fidelity-2 Ultrafast Fiber Oscillator','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('720','Fidelity-2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('721','Fidelity HP Ultrafast Fiber Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('722','Fidelity-HP 10','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('723','Fidelity-HP 18','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('724','RAPID FX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('725','Opera-F and Opera-HP for Monaco','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('726','Opera-F','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('727','Opera-HP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('728','Pulse Switch for Mira 900','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('729','Pulse Switch for Mira 900 (Femtosecond Configuration)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('730','Pulse Switch for Mira 900 (Picosecond Configuration)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('731','META 1.5C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('732','META 2C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('733','META 4C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('734','META 10C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('735','Harmonic Generator','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('736','HGS-D','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('737','HGS-F','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('738','HGS-T','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('739','Pulse Picker','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('740','OPA 9800/9850','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('741','OPA 9400','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('742','OPA 9450','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('743','OPA 9800','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('744','OPA 9850','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('745','Conduction Cooled Package (CCP)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('746','CCP 780/830 nm - 60W 18FF','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('747','CCP 780/830 nm - 60W 18FF PulseLife','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('748','CCP 780/830 nm - 40W 30FF','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('749','CCP 780/830 nm - 40W 30FF PulseLife','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('750','CCP 780/830 nm - 50W 30FF','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('751','CCP 780/830 nm - 80W 28FF','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('752','CCP 780/830 nm - 80W 28FF PulseLife','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('753','CCP 780/830 nm - 250W QCW PulseLife','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('754','CCP 870/890 nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('755','CCP 965/985 nm - 60W 10FF','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('756','CCP 965/985 nm - 80W 18FF','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('757','CCP 1060 nm - 40W 20FF','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('758','CCP 1060 nm - 80W 50FF','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('759','CCP 1430/1470 nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('760','FAP 600 Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('761','FAP600-22W-975.0to980.0-F<4.5-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('762','FAP600-25W-800to820nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('763','FAP600-25W-805.0to811.0-F<3.5-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('764','FAP600-22W-975.0to980-F<4.5-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('765','FAP600-25W-800to820nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('766','FAP600-25W-805.0to811.0-F<3.5-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('767','FAP600-50W-800.0to820.0-FW90E<8.0-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('768','Fiber Coupled Laser Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('769','FAP600-25W-805.0to811.0-F<3.5-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('770','FAP600-50W-800.0to820.0-FW90E<8.0-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('771','FAP800-30W-805.0to811.0-F<3.5-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('772','FAP800-30W-805.0to811.0-F<3.5-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('773','FAP800-40W-805.0to811.0-F<3.5-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('774','FAP800-L-30W-803.0to809.0-F<3.0-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('775','FAP800-R-40W-930.0to950.0-F<6.0-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('776','FAP800-R-40W-970.0to990.0-F<6.0-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('777','FAP800-50W-805.0to811.0-FW90E<4.5-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('778','FAP800-70W-800.0to820.0-FW90E<5.0-25C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('779','G-Stack Diode Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('780','Horizontal Arrays','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('781','PulseLife CW Horizontal Array - 2 Bar Arrays 80W','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('782','PulseLife CW Horizontal Array - 2 Bar Arrays 100W','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('783','PulseLife CW Horizontal Array - 3 Bar Arrays 120W','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('784','PulseLife CW Horizontal Array - 3 Bar Arrays 150W','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('785','PulseLife QCW Horizontal Array - 5 Bar Arrays 500W','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('786','PulseLife QCW Horizontal Array - 5 Bar Arrays 1000W','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('787','PulseLife G-Stack - GH2-7','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('788','PulseLife G-Stack - GH8-16','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('789','Single Emitter Diode Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('790','Single Emitter Diode Lasers, 780-830 nm - 1.6W 100 μm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('791','Single Emitter Diode Lasers, 780-830 nm - 3.2W 90 μm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('792','Single Emitter Diode Lasers, 780-830 nm - 2.5W 150 μm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('793','Single Emitter Diode Lasers, 780-830 nm - 5W 140 μm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('794','Single Emitter Diode Lasers, 780-830 nm - 7W 200 μm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('795','Unmounted Diode Laser Bars (UMB)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('796','Unmounted Diode Laser Chips (UMCs), 780-830 nm - 3W 100 μm x 2mm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('797','Unmounted Diode Laser Chips (UMCs), 780-830 nm - 3.5W 100 μm x 2mm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('798','Unmounted Diode Laser Chips (UMCs), 780-830 nm - 5W 200 μm x 2mm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('799','Unmounted Diode Laser Chips (UMCs), 780-830 nm - 7W 200 μm x 2mm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('800','Unmounted Diode Laser Bars (UMBs) 780-830 nm - 40W 18FFx2mm TE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('801','Unmounted Diode Laser Bars (UMBs) 780-830 nm - 60W 18FFx2mm TE-Plus','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('802','Unmounted Diode Laser Bars (UMBs) 780-830 nm - 40W 30FFx1mm TM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('803','Unmounted Diode Laser Bars (UMBs) 780-830 nm - 50W 30FFx1.5mm TM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('804','Unmounted Diode Laser Bars (UMBs) 780-830 nm - 60W 28FFx2mm TE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('805','Unmounted Diode Laser Bars (UMBs) 780-830 nm - 80W 28FFx2mm TE-Plus','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('806','Unmounted Diode Laser Bars (UMBs) 780-830 nm - 60W 50FFx1mm TM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('807','Unmounted Diode Laser Bars (UMBs) 780-830 nm - 100W 50FFx2mm TE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('808','Unmounted Diode Laser Bars (UMBs) 780-830 nm - 200W QCW 90FFx1mm TM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('809','Unmounted Diode Laser Bars (UMBs) 780-830 nm - 300W QCW 90FFx1.5mm TE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('810','Unmounted Diode Laser Bars (UMBs) 780-830 nm - 500W QCW 50FFx1.5mm TE-Plus','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('811','Unmounted Diode Laser Bars (UMBs) 780-830 nm - 500W QCW 80FFx2mm TE-Plus','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('812','Unmounted Diode Laser Bars (UMBs), 965-985 nm - 60W 10FFx4mm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('813','Unmounted Diode Laser Bars (UMBs), 965-985 nm -100W 18FFx4mm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('814','Unmounted Diode Laser Bars (UMBs), 965-985 nm -150W 30FFx4mm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('815','Unmounted Diode Laser Bars (UMBs), 1060 nm - 40W 20FFx1mm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('816','Unmounted Diode Laser Bars (UMBs), 1060 nm - 100W 50FFx1.5mm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('817','Unmounted Diode Laser Bars (UMBs), 1430-1470 nm - 20% fill factor bars (19 x 100 μm emitters)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('818','Astrella Integrated Ti:S Amplifier','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('819','Astrella-1K-USP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('820','Astrella-1K-F','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('821','EnergyMax Laser Sensors','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('822','J-50MUV-248','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('823','J-50MUV-193','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('824','J-25MUV-193','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('825','J-25MUV-248','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('826','J-50MT-10KHZ','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('827','J-25MT-10KHZ','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('828','J-10MT-10KHZ','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('829','J-50MB-HE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('830','J-50MB-LE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('831','J-25MB-LE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('832','J-25MB-HE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('833','J-10MB-HE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('834','J-10MB-LE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('835','J-25MB-IR','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('836','J-50MB-YAG','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('837','J-50MB-IR','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('838','EnergyMax-USB/RS Sensors','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('839','EnergyMax-RS J-10SI-HE Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('840','EnergyMax-RS J-10MB-LE Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('841','EnergyMax-RS J-10MB-HE Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('842','EnergyMax-RS J-50MB-YAG Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('843','EnergyMax-RS J-25MB-LE Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('844','EnergyMax-RS J-50MB-HE Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('845','EnergyMax-RS J-50MT-10KHZ Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('846','EnergyMax-USB J-10SI-HE Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('847','EnergyMax-USB J-10MB-LE Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('848','EnergyMax-USB J-10MB-HE Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('849','EnergyMax-USB J-50MB-YAG Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('850','EnergyMax-USB J-25MB-LE Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('851','EnergyMax-USB J-25MB-HE Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('852','EnergyMax-USB J-50MB-LE Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('853','EnergyMax-USB J-50MB-HE Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('854','EnergyMax-USB J-10MT 10KHZ Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('855','EnergyMax-USB J-25MT-10KHZ Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('856','EnergyMax-USB J-50MT-10KHZ Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('857','EnergyMax-USB J-25MUV-193 Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('858','EnergyMax-USB J-50MUV-248 with Diffuser Energy Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('859','Laser Beam Diagnostics','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('860','BM Mount','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('861','BeamMaster-USB BM-3 Si-Enhanced','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('862','BeamMaster-USB BM-7 Si-Enhanced','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('863','BeamMaster-USB Bm-3 InGaAs (3mm)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('864','BeamMaster-USB Bm-7 InGaAs (3mm)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('865','BeamMaster-USB Bm-7 InGaAs (5mm)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('866','BM C-Mount','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('867','LaserCam-HR II','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('868','LaserCam-HR II 1/2"','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('869','LaserCam-HR II 2/3"','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('870','LaserCam-HR-InGaAs','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('871','LaserCam-HR-UV','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('872','ModeMaster PC M-Squared (M2) Beam Propagation Analyzer','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('873','ModeMaster PC System UV, Low-Divergence','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('874','ModeMaster PC system, UV, High-Divergence','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('875','ModeMaster PC System VIS Low-Divergence','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('876','ModeMaster PC System, VIs, High-Divergence','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('877','ModeMaster PC System, NIR, Low-Divergence','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('878','ModeMaster PC System, NIR, High-Divergence','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('879','ModeMaster PC System, IR High Divergence','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('880','ModeMaster PC System, IR Low Divergence','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('881','WaveMaster','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('882','Silicon Detector 0.22 to 1.0 μm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('883','Germanium Detector 0.8 to 1.8 μm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('884','High-Divergence Lens Kit','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('885','High-Divergence Lens Kit','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('886','Low-Divergence Lens Kit','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('887','Laser Power and Energy Meters','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('888','LabMax-TOP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('889','LabMax-Pro SSIM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('890','LabMaxTOP with GPIB','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('891','LabMax-TO','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('892','FieldMaxII-TOP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('893','FieldMaxII-P','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('894','FieldMaxII To','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('895','FieldMate','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('896','Laser Check','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('897','S-1592 Android Mobile System Bundle','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('898','S-1593 iOS Mobile System Bundle','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('899','Sensors - Laser Power','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('900','PM10','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('901','PM30','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('902','PM2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('903','PM150-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('904','PM150','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('905','PM10X','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('906','PM150X','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('907','PM2X','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('908','PM100-19C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('909','PM30X','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('910','PM300F-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('911','PM200F-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('912','PM200F-19','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('913','PM300F-50X','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('914','PM300F-19','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('915','PM200F-50X','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('916','PM1K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('917','PM5K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('918','PM3K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('919','PM300','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('920','LM-2 VIS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('921','OP-2 VIS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('922','LM-2 IR','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('923','LM-2 UV','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('924','OP-2 UV','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('925','OP-2 IR','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('926','PM3','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('927','PS19Q','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('928','PS10','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('929','PS10Q','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('930','PS19Q','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('931','PM3Q','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('932','PM5K-100','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('933','PM1K-100','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('934','PM5K-200','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('935','PM3K-100','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('936','PM150-19B','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('937','PM1K-36B','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('938','PM10-19A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('939','PM10-19B','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('940','PM150-50B','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('941','PM150-19A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('942','BeamFinder','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('943','PM150-50XB','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('944','PM150-50A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('945','PM10V1','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('946','PM30V1','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('947','LM-10 HTD','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('948','LM-45 HTD','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('949','LM-3 HTD','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('950','LM-100 HTD','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('951','LM-150FS HTD','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('952','LM-1000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('953','LM-5000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('954','LM-2500','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('955','PM10-19C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('956','PM150-50C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('957','PM150-50XC','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('958','PM150-19C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('959','PowerMax-Pro Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('960','PowerMax-Pro 150F HD','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('961','PowerMax-Pro 150 HD','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('962','PowerMax-Pro HP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('963','PowerMax-Pro 150F BB','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('964','PowerMax-Pro 150 BB','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('965','PowerMax-Pro 150 HD Nano','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('966','PowerMax-Pro 150 BB Nano','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('967','PowerMax-Pro 150F Nano','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('968','PowerMax-Pro USB/RS Sensors','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('969','PowerMax-Pro USB/RS 150 HD','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('970','PowerMax-Pro USB/RS 150 HD Nano','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('971','PowerMax-Pro USB/RS 150F HD','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('972','PowerMax-Pro USB/RS 150F HD Nano','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('973','PowerMax-Pro USB/RS 150 BB','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('974','PowerMax-Pro USB/RS 150F BB','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('975','kW PowerMax-Pro Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('976','PMP 1kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('977','PMP 1kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('978','PMP 1kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('979','PMP 1kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('980','PMP 1kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('981','PMP 3kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('982','PMP 3kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('983','PMP 3kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('984','PMP 3kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('985','PMP 3kW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('986','PowerMax USB/RS Sensors','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('987','PowerMax-USB LM-10 Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('988','PowerMax-USB LM-1000 Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('989','PowerMax-USB LM-20 Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('990','PowerMax-USB LM-200 110V Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('991','PowerMax-USB LM-200 220V Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('992','PowerMax-USB LM-200B','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('993','PowerMax-USB LM-3 Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('994','PowerMax-USB LM-45 Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('995','PowerMax-USB LM-5000 Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('996','PowerMax-USB PM10 Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('997','PowerMax-USB PM10-19C Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('998','PowerMax-USB PM150-19C Power Sensor','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('999','PowerMax-USB PM150-50C Power Sensor Sensor','');
