INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('821','Deep UV','', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('822','Deep UV','50', '0.0005');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('823','Deep UV','50', '0.000125');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('824','Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('825','Deep UV','25', '0.000125');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('826','Deep UV','50', '0.0005');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('827','Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('828','Deep UV','10', '1.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('829','Deep UV','50', '0.001');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('830','Deep UV','50', '0.00025');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('831','Deep UV','25', '2.5E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('832','Deep UV','25', '0.0005');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('833','Deep UV','10', '1.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('834','Deep UV','10', '3.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('835','Visible','25', '0.0015');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('836','Deep UV','50', '0.0015');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('837','Visible','50', '0.001');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('838','Deep UV - IR','', '0.00E+0.00');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('839','IR','10', '0.00E+0.00');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('840','Deep UV','10', '5.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('841','Deep UV','10', '1.2E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('842','Deep UV','50', '0.0024');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('843','Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('844','Deep UV','50', '0.0016');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('845','Deep UV','50', '0.0004');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('846','IR','10', '0.00E+0.00');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('847','Deep UV','10', '5.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('848','Deep UV','10', '1.2E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('849','Deep UV','50', '0.0024');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('850','Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('851','Deep UV','25', '0.00085');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('852','Deep UV','50', '0.0004');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('853','Deep UV','50', '0.0016');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('854','Deep UV','10', '3.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('855','Deep UV','25', '9.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('856','Deep UV','50', '0.0004');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('857','Deep UV','25', '9.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('858','Deep UV','50', '0.0008');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('860','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('867','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('868','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('869','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('870','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('871','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('872','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('873','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('874','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('875','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('876','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('877','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('878','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('879','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('880','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('881','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('887','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('888','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('889','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('890','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('891','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('892','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('893','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('894','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('895','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('896','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('897','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('898','','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('899','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('900','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('901','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('902','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('903','Visible','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('904','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('905','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('906','Visible','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('907','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('908','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('909','Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('910','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('911','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('912','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('913','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('914','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('915','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('916','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('917','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('918','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('919','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('920','Violet','7.9', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('921','Violet','7.9', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('922','Near IR','5', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('923','Deep UV','6', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('924','Deep UV','6', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('925','Near IR','5', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('926','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('927','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('928','Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('929','Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('930','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('931','Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('932','Deep UV','100', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('933','Deep UV','100', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('934','Deep UV','200', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('935','Deep UV','100', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('936','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('937','Deep UV','36', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('938','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('939','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('940','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('941','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('942','Deep UV','35', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('943','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('944','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('945','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('946','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('947','Deep UV','16', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('948','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('949','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('950','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('951','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('952','Deep UV','38', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('953','Deep UV','55', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('954','Deep UV','55', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('955','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('956','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('957','Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('958','Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('959','Deep UV - Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('960','UV','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('961','UV','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('962','Near IR','25 (diameter)', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('963','Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('964','Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('965','Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('966','Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('967','Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('968','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('969','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('970','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('971','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('972','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('973','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('974','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('975','Near IR - IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('976','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('977','IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('978','IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('979','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('980','IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('981','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('982','IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('983','IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('984','Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('985','IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('986','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('987','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('988','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('989','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('990','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('991','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('993','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('994','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('995','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('996','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('997','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('998','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('999','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1000','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1001','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1002','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1003','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1004','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1005','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1006','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1007','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1008','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1009','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1010','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1011','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1012','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1013','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1014','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1015','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1016','Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('1043','','', '');
