INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0005');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0005');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.000125');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.000125');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '0.000125');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '0.000125');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0005');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0005');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '1.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '1.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.001');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.001');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.00025');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.00025');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '2.5E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '2.5E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '0.0005');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '0.0005');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '1.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '1.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '3.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '3.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','25', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','25', '0.0015');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','25', '0.0015');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0015');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0015');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','50', '0.001');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','50', '0.001');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV - IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV - IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV - IR','', '0.00E+0.00');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV - IR','', '0.00E+0.00');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','10', '0.00E+0.00');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','10', '0.00E+0.00');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '5.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '5.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '1.2E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '1.2E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0024');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0024');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0016');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0016');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0004');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0004');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','10', '0.00E+0.00');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','10', '0.00E+0.00');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '5.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '5.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '1.2E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '1.2E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0024');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0024');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '5.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '0.00085');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '0.00085');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0004');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0004');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0016');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0016');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '3.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '3.0E-7');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '9.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '9.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0004');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0004');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '9.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','25', '9.0E-5');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0008');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '0.0008');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Visible','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','7.9', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','7.9', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','5', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','6', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','6', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','5', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','10', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','100', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','100', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','200', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','100', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','36', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','35', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','16', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','38', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','55', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','55', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','50', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','19', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV - Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('UV','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('UV','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('UV','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('UV','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','25 (diameter)', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','25 (diameter)', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Violet','30 x 30', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR - IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Near IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('IR','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('Deep UV','', '');
INSERT INTO `magento_export` (`ID`,`Wavelength`,`Active_Area_Diameter`,`Min_Energy`) VALUE ('','', '');
