INSERT INTO `pd_applications_beta` (`Title`) VALUES ('');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('1310 and 1550 nm Components');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('193 nm Multicollector ICP-Ms');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('2 µm pulsed lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('2 µm pulsed lasers Remote sensing & LIDAR');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('2 μm fiber lasers for pumping crystal lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('2D/3D Cutting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('2µm beam delivery');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('3D Contour Mapping');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('3D Package Manufacturing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('3D Printing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('3D Profiling');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('3D-Structuring');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('980/1550 nm WDM couplers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('ASE source for full-field imaging');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('ASE sources');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('ASE sources for spectroscopy and fiber sensors');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ablating');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ablation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Absolute Frequency');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Activation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Additive Manufacturing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Advanced Packaging and Interconnects');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Aesthetics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Airframe');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Alignment');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Amplifier Seeding');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('An alternative to Yb-doped fibers for 1060 nm operation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Annealing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Applications wanting a simple Analog or Digital inputs to control the laser');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Applications wanting thermal management (cooling) for the lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Applied Physics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Astronomy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Atom Cooling and Transportation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Atom Cooling and Trapping');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Atomic and Molecular');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Automobile Components');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Automotive');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Automotive Cylinder');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Automotive Industry');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Automotive and Electronic Components');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Beam Delivery for Pulsed Lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Beam delivery cables');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Benchtop Analyzers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Beverage');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Bi-directional splitters and combiners');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Bio-Detection and Analysis');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Bio-medical');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Biology');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Blue laser diode pigtailing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Bragg Gratings and Waveguides');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Bridge Fiber');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Brillouin distributed temperature & strain sensing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Brillouin distributed temperature &strain sensing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('C+L Band Gratings');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('CATV and Telecom amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('CATV and data comm.');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('CATV couplers; Tap couplers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('CATV pump/signal couplers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('CRS/SRS');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('CW amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('CW and pulsed amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('CW and pulsed fiber lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('CW fiber amplifiers and lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Calibration');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ceramic Drilling and Scribing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ceramic Processing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Cladding');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Cleaning');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Coating Removal');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Coherent Anti-stokes Raman Scatterint (CARS) Microscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Compact ASE sources');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Compact C and L-band Components');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Compact Flow Cytometer');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Compact UV sources');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Complex Layer Processing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Components fiber for optical devices');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Confocal Microscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Connectivity between source laser and modulator');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Continuous Wave OPO');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Converting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Couplers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Couplers (including WDM)');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Couplers Optical switches');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Couplers and combiners');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Couplers and pump combiners');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Cutting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Cutting Metal');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Cytometry');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('DIAMOND Like Carbon Coating');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('DIAMOND and Eye Glass');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('DIAMOND and Eye Glass Marking');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('DNA Sequencing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('DWDM Broadband');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('DWDM gain flattening filters');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Defense');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Defense & Military');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Defense and Military');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Dermatology and surgical lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Die Board Cutting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Diode Pigtails');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Diode pigtailing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Diode pigtails');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Dispersion compensators');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Display');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Dopant Activation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Doping');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Down Hole Instrumentation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Drilling');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Edge Deletion of Solar Cells');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Electronics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Electronics Industry');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Endoscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Engraving');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Engraving Laser');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Enhanced oil recovery processes');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Entertainment');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Etch Barrier Patterning');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Etching');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Excimer Laser Annealing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Eye Safe (~2  µm) lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Eye Safe (~2 µm) lasers & amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Eye Safe (~2 μm) lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Eye Safe (~2µm) lasers & amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Eye Safe industrial & medical lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Eye Safe industrial and medical lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Eye safe (1.5 µm) lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Eye safe (1.5 μm) lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Eye-safe amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Eye-safe lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('EyeSafe industrial and medical lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('FBG and Fabry-Perot based sensors');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('FTTH');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('FTTx Components and modules');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Femtosecond fiber lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fiber Bragg Grating');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fiber amplifier pumps');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fiber coupled diode lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fiber optic gyroscopes (FOGs)');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fiber optic gyroscopes(FOGs)');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fiber optic interferometers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fiber optic probes');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fiber optic sensors');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fiber optic voltage and current sensors');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fiber tails for high NA sources');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fibertails for Planar Waveguides');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Film Cutting and Processing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fine Metal Machining');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fine metal machining');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Flamentation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Flex Materials Cutting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Flex PCB drilling & cutting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Flexible Small Volume Production');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Flow Cytometry');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Flow Visualization');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fluid Inclusion Research');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fluorescence Lifetime Imaging');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fluoride and other non-silica fibers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Food');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Functional Surface Treatment');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Fused fiber couplers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Gain flattening filters');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Gemstone Fingerprinting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Genetics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Genomics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Genomics and Proteomics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Glass Cutting & Drilling');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Glass Cutting and Drilling');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Glass Cutting and Thermal Processing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Glass Micromaching');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Graphic Arts');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Grating stabilizers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Grating-based pump diode pigtails');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Gravitational Wave Studies');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Hard');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Hard Soldering');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Hardening');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Heat Treatment');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Heating');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High Energy Physics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High Harmonic Generation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High Power Laser Locking & Speeding');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High Precision Machining of Medical Parts');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High Speed Digital Converting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High Temperature');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High Throughput Drug Screening');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High Throughput Screening');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High peak power');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High peak power amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High peak power amplifiers LIDAR Material processing Non-linear optics/frequency doubling');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High peak power lasers & amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High peak power pulsed amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High peak power pulsed fiber amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High peak power pulsed fiber amplifiers & lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High power 2 µm CW and pulsed lasers & amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High power CW and pulsed EyeSafe (~2  μm) lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High power CW and pulsed EyeSafe (~2 µm) lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High power CW and pulsed EyeSafe (~2 μm) lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High power beam delivery');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High power fiber lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High power lasers & amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High power lasers and amplifiers emitting around 1.5 μm');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High power pulsed fiber lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High power pump & signal pigtails');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High pulse energy amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('High-Speed SHADOW Applications');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Holography');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Hydrogen Insensitive');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Hydrothermal well temperature measurements');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('IC Package Trimming');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('IC Package singulation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('IR sources for frequency doubling');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ideal for Bragg gratings in laser applications');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Illumination');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Industrial');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Industrial Microprocessing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Industrial and Medical');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ink-Jet Nozzle Drilling');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Inside Glass Marking');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Inspection');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Inspection and Process Including Environmental Control');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Interferometric');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Interferometric sensors');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Interferometry');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Isolators');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Isotope Ratio Determination');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Kiss-Cutting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('L-band amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('LED Dicing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('LED Package Marking');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('LIDAR');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('LIDAR Eye-safe lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('LIDAR Material processing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('LIDAR Non-linear optics / frequency doubling');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('LIDAR Range finding');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('LLO - Laser Lift-Off');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('LMA fiber couplers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('LMA fiber couplers & pump combiners');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laboratories needing CDRH features');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Large bandwidth tactical cables');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Additive Manufacturing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Direct Imaging');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Direct Patterning');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Entertainment');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Fusion Optics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Induced Fluorescence Spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Inspection');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Lift-Off');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Lift-Off Separation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Light Show');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Micro Dissection');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Pumping');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Trimming of Embedded Passives with Diode- Pumped Solid-State Lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser Vision Correction');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser and amplifiers at 1.5 mm (CATV and Telecom)');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser and amplifiers for 20 - 30 W at 1.5 mm (CATV and Telecom)');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser delivery / fluorescence');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser delivery in spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser delivery/fluorescence');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser diode pigtails');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser diode pigtails. Fused fiber couplers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser marking');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser pig-tailing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Laser pigtailing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Life Sciences');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Lithium niobate modulators');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Low NA planar waveguides');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Low power CW and pulsed fiber lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Low to mid power CW and pulsed Eye Safe (~2  μm) lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Low to mid power CW and pulsed Eye Safe (~2 µm) lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Low to mid power CW and pulsed Eye Safe (~2 μm) lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Low to mid power CW and pulsed lasers & amplifiers at 2µm');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Low-K Scribing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('MALDI-TOF Spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Machine Vision');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Making Micro-Reactors (lab-on-a-chip)');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Marine Sediment Analysis');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Marking');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Marking Laser');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Marking of Complex Plastic Structures');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Material Processing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Material Science and Engineering');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Material marking');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Material processing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Materials Processing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Materials processing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Medical');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Medical Applications');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Medical Diagnostics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Medical Imaging');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Medical Imaging and Instrumentation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Medical Industry');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Medical and Dental');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Medical and Life Sciences');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Metals and Polymers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Metro Components');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Metro amps');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Metrological');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Metrology');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Micro Array Scanning');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Micro-Machining');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Micro-Structuring');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Microelectronics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Microelectronics and Consumer Electronics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Micromachining');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Micromachining of Glass and Sapphire Parts');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Microscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Mid power CW lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Military');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Military and commercial LIDAR');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Military and commercial lidar');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Miniature fiber optic packages');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Missile and UAV optical interconnects');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Monolithic high power lasers & amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Monolithic high power lasers & amplifiers LMA fiber couplers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Monolithic high power lasers& amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Multi-kW');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Multidimensional Spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Multiphoton Excitation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Multiphoton Excitation (MPE)');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Multiphoton Excitation (MPE) Imaging');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Multiphoton Excitation (MPE) Microscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Multiple fiber wraps on a mandrel');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Multiplexers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Nanostructuring');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Non-Linear Optics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Non-Linear Optics Studies');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Non-Linear Spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Non-linear Optics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Non-linear optics / frequency doubling');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Non-linear optics/frequency doubling');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('OADM');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('OCT medical imaging Components/couplers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('OPA Pumping');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('OPO Pumping and Non-Linear Optics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Oil & Gas well production monitoring');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Oil reservoir engineering and flow optimization');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Oil reservoir optimization');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ophthalmic');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Opthalmology');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Optical');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Optical Heterodyning & Coherent Communication');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Optical Hterodyning and Coherent Communication');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Optical Metrology');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Optical Tweezers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Optical pump & beam delivery');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Optogenetic Excitation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Optogenetic Photoactivation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Optogenetics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Optogenetics (Photo Activation)');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('PM amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('PM fiber amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('PM patchcords');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('PMD compensators');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Particle Counting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Percussion Drilling of Small Apertures for Injector Nozzles in Metal');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Perforation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pharmaceutical Packaging');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Photochemistry');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Photomask Inspection');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Physical Chemistry');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Physics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pigtail fiber for visible red diodes');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pigtailing 2µm Components');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pigtailing in small form metro Components');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Planar Waveguides');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Plastic Welding');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Polarization sensitive devices');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Polarization-sensitive Components');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Polarized lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Polyimide Version');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Polymer Marking');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pre-amps for high-power');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Precise Metal Marking & Cutting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Precise Metal Marking and Cutting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Precision Cutting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Precision Engineering');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Precision Material');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Precision Welding');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Printing & Embossing Tools');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Printing and Embossing Tools');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Process Acrylics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Process Cardboard');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Process Ceramics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Process Development');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Process Glass');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Process Leather');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Process PCBs');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Process Paper');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Process Polymer Films');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Process Textiles');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Process Wood');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Processing Ceramics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Production');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pulsed Laser Deposition');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pulsed fiber lasers and amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pulsed fiber lasers and amplifiers Material processing LIDAR Non-linear optics / frequency doubling &nbsp');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pump Diode Pigtails');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pump and signal pigtails');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pump and source pigtails');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pump combiners');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pump diode pigtails');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pump pigtails');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pump stabilizers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pumping');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pumping of Ho-doped lasers & amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Pumping of Optical Parametric Oscillators (OPO)');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Quantum Optics Studies');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Quantun Optics Studies');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('RGB Components');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('RGB imaging systems');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Raman Spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Raman Spectrscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Raman amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Raman distributed temperature sensing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Raman gain modules');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Raman spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Range finding');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Range finding CW fiber amplifiers and lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Rapid Prototyping');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Remote Sensing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Remote and Scanner-based Applications');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Remote sensing & LIDAR');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Robust duty in extreme environments');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Robust duty in extreme military and classified environments');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Roll-To-Roll Circuit Patterning');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('SAGD recovery optimization');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Satellite Optics');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Scanner-based Applications');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Scanning');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Scientific');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Scribing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Scribing Applications');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Scribing Automobiles');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Scribing and Thin Film Processing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Second Harmonic Generation Imaging');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Semiconductor Annealing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Semiconductor Inspection');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Semiconductor Manufacturing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Semiconductor Manufacturing Display');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Semiconductor Processing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Sensing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Sensors');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Sequential Lateral');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Short pulse fiber amplifiers & lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Short pulse fiber amplifiers and lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Silicon Photonics Devices');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Silicon Wafer scribing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Silicon photonics devices');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Single and multi-channel C-band amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Single clad Yb-fiber pigtails');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Single clad and double clad devices');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Single frequency systems');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Single-mode applications');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Small form factor Components');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Small form factor amps');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Small form factor couplers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Small form factor packages');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Solar');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Solar Cell Scribing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Solar P1 to P3');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Soldering');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Solid Sample Analysis');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Solid State Research');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Solid-State Laser Pumping');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Solid-state Laser Pumping');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Solidification');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Sources for optical coherence tomography and frequency resolved');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Spacecraft');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Specialty sensors');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Spectroscopy and instrumentation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Spectrscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Stent Fabrication');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Stimulated Raman Scattering');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Stimulated Raman Scattering (SRS) Microscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Structuring');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Supercontinuum Generation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Surface Cleaning');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Surface SFG/SHG');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Surface Spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Surface Treatment');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('TCO Structuring');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('THz Spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Telecom FDDI');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Telecom amplifiers Laser delivery/fluorescence');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Terahertz Generation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Terahertz Imaging');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Testing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Thin Film Patterning/Ablation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Thin Film Scribing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Thin-Film Ablation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Thin-Film Scribing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Thin-film Scribing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Third Harmonic Generation Imaging');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Through-Cutting');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ti:Sapphire Pumping');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Tight bend radius conditions');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Time Resolved Luminescence and Spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Time-Resolved');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Time-Resolved Spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Time-resolved Spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Tm-fiber lasers/amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Transient Absorption Spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Transparent Material Scribing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Transparent Material Welding');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Trapping');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Trimming');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Two-Photon Polymerization');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('U/Pb-Age Dating in Zircons');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('UV Annealing and Implant Activation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ultra-compact Components requiring small bend radii');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ultra-fast (~2  μm) fiber lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ultra-short pulse fiber amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ultra-short pulse laser');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ultra-short very narrow linewidth all-optical DFB and DBR lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ultrafast (fs) fiber lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Ultrafast Spectroscopy');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Via Hole Drilling');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Voltage and current sensors');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('WDM');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('WDM pump/signal couplers for EDFAs');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Wafer Scribing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Wafer Scribing and Singulation');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Wafer and Reticle Inspection');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Waveguide Writing');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Welding');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('Wire Stripping');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('and Decorative Coatings');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('double-clad devices');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('etc.');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('fs Micromachining');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('industrial and medical');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('medical and metrological applications');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('missile and UAV optical interconnects');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('multimode lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('pulsed fiber amplifiers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('pump combiners & FBG');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('pump combiners& FBG');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('spacecraft');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('~ 2 µm output TEM00 fiber lasers for pumping solid state crystal lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('~2 µm output TEM00 fiber lasers for pumping solid state crystal lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('~2 μm output TEM00 fiber lasers for pumping solid state crystal lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('~2 μm output TEM00 fiber lasers for pumping solid state crystal lasers &nbsp');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('~2µm output TEM00 fiber lasers for pumping solid state crystal lasers');
INSERT INTO `pd_applications_beta` (`Title`) VALUES ('µ-via drilling');
