INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','APPLICATIONS');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Laser Inspection');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Wafer and Reticle Inspection');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Machine Vision');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Life Sciences');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Confocal Microscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','DNA Sequencing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Flow Cytometry');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Medical Imaging and Instrumentation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Materials Processing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Marking');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Cutting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Engraving');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Film Cutting and Processing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Process Acrylics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Process Cardboard');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Process Ceramics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Process Glass');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Process Polymer Films');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Process Leather');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Process Paper');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Process Textiles');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Process Wood');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Process PCBs');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Medical and Dental');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Food');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Beverage');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Pharmaceutical Packaging');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Microelectronics and Consumer Electronics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Automotive and Electronic Components');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Holography');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Scientific');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Particle Counting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Microscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Laser Light Show');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Laser Entertainment');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Defense and Military');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Medical');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Interferometry');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Entertainment');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Microelectronics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Raman Spectroscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Graphic Arts');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Medical and Life Sciences');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Benchtop Analyzers');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Bio-Detection and Analysis');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Compact Flow Cytometer');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Opthalmology');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Medical Imaging');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Optogenetics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Genomics and Proteomics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','High Throughput Drug Screening');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Medical Diagnostics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Semiconductor Inspection');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Micro Array Scanning');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Metrology');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Inspection');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Cytometry');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Genetics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','High Throughput Screening');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','3D Profiling');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Industrial');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Amplifier Seeding');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Atom Cooling and Trapping');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Continuous Wave OPO');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Pumping');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Advanced Packaging and Interconnects');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','High Speed Digital Converting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Through-Cutting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Kiss-Cutting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Perforation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Die Board Cutting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Glass Cutting and Thermal Processing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Ceramic Drilling and Scribing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Automotive');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','3D Printing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Semiconductor Processing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Glass Cutting & Drilling');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Micromachining');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Ceramic Processing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Converting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Drilling');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Scribing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','µ-via drilling');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Thin-film Scribing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Flex PCB drilling & cutting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','IC Package singulation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Silicon Wafer scribing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Fine Metal Machining');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Flex Materials Cutting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','3D Package Manufacturing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','IC Package Trimming');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Wafer Scribing and Singulation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Solar Cell Scribing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Via Hole Drilling');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Diamond and Eye Glass');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Laser Vision Correction');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Rapid Prototyping');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Wire Stripping');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Glass Cutting and Drilling');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Ink-Jet Nozzle Drilling');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','TCO Structuring');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Printing and Embossing Tools');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Printing & Embossing Tools');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Semiconductor Manufacturing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Display');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Photomask Inspection');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','3D-Structuring');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Etch Barrier Patterning');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Roll-To-Roll Circuit Patterning');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Diamond Like Carbon Coating');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Pulsed Laser Deposition');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','LLO - Laser Lift-Off');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Micro-Structuring');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Interferometric');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Nanostructuring');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Laser Lift-Off');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Fiber Bragg Grating');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Production');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Dopant Activation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Laser Direct Patterning');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Surface Treatment');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Optical Tweezers');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Trapping');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Marking of Complex Plastic Structures');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Laser Trimming of Embedded Passives with Diode- Pumped Solid-State Lasers');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Inside Glass Marking');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','LED Package Marking');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Solar P1 to P3');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Industrial Microprocessing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Solar');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Precise Metal Marking and Cutting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Semiconductor Manufacturing Display');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','LED Dicing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Medical Applications');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','3D Contour Mapping');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Excimer Laser Annealing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Doping');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Laser Direct Imaging');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Thin Film Scribing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Multiphoton Excitation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Terahertz Imaging');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','CRS/SRS');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Atomic and Molecular');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Spectroscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Multiphoton Excitation (MPE)');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Non-linear Optics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Time Resolved Luminescence and Spectroscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Optogenetic Photoactivation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Second Harmonic Generation Imaging');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Supercontinuum Generation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Pumping of Optical Parametric Oscillators (OPO)');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Time-resolved Spectroscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Multidimensional Spectroscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','THz Spectroscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','fs Micromachining');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Surface SFG/SHG');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Stimulated Raman Scattering');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','High Harmonic Generation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Biology');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Photochemistry');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Solid State Research');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Applied Physics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Physical Chemistry');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Bragg Gratings and Waveguides');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Glass Micromaching');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Ultrafast Spectroscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Multiphoton Excitation (MPE) Imaging');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Material Processing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Waveguide Writing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Material Science and Engineering');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Physics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Raman Spectrscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Terahertz Generation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Welding');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Cladding');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Annealing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Heat Treatment');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Transparent Material Scribing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Transparent Material Welding');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Thin Film Patterning/Ablation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Optical');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Hard');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','and Decorative Coatings');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Precision Engineering');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Scribing Applications');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Medical Industry');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Automotive Industry');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Precision Cutting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Electronics Industry');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Precision Welding');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','High-Speed SHADOW Applications');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','2D/3D Cutting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Cutting Metal');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Automobile Components');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Scribing Automobiles');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Complex Layer Processing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','OPA Pumping');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Ophthalmic');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Precise Metal Marking & Cutting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Thin-Film Ablation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Wafer Scribing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Stent Fabrication');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Laser Induced Fluorescence Spectroscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','MALDI-TOF Spectroscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Laser Micro Dissection');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','LIDAR');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Inspection and Process Including Environmental Control');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Ti:Sapphire Pumping');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Semiconductor Annealing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Flow Visualization');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Gravitational Wave Studies');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','High Power Laser Locking & Speeding');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Optical Metrology');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Optical Heterodyning & Coherent Communication');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Quantum Optics Studies');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Spectrscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Non-Linear Optics Studies');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Atom Cooling and Transportation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Quantun Optics Studies');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Absolute Frequency');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Calibration');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Optical Hterodyning and Coherent Communication');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Automotive Cylinder');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Hardening');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Sequential Lateral');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Solidification');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Solid Sample Analysis');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Isotope Ratio Determination');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Fluid Inclusion Research');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','U/Pb-Age Dating in Zircons');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Marine Sediment Analysis');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','193 nm Multicollector ICP-Ms');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Gemstone Fingerprinting');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Processing Ceramics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Metals and Polymers');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Making Micro-Reactors (lab-on-a-chip)');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Process Development');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Flexible Small Volume Production');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','UV Annealing and Implant Activation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Laser Lift-Off Separation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Time-Resolved');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Non-Linear Spectroscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Multiphoton Excitation (MPE) Microscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Optogenetic Excitation');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Optogenetics (Photo Activation)');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','OPO Pumping and Non-Linear Optics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Two-Photon Polymerization');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Scribing and Thin Film Processing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Functional Surface Treatment');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Percussion Drilling of Small Apertures for Injector Nozzles in Metal');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','High Precision Machining of Medical Parts');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Low-K Scribing');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Micromachining of Glass and Sapphire Parts');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Surface Spectroscopy');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Diamond and Eye Glass Marking');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Laser Pumping');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Illumination');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Aesthetics');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Solid-State Laser Pumping');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Plastic Welding');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Soldering');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Heating');
INSERT INTO `pd_applications` (`ID`,`Title`) VALUES ('','Hard Soldering');
