INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('1','Azure','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('2','ColdRay Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('3','ColdRay-375','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('4','ColdRay-405','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('5','ColdRay-445','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('6','ColdRay-473','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('7','ColdRay-640','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('8','ColdRay-660','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('9','Compass 115M','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('10','CUBE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('11','CUBE 375-16C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('12','CUBE 405-50C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('13','CUBE 405-100C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('14','CUBE 445-40C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('15','CUBE 488-50C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('16','CUBE 640-40C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('17','CUBE 640-100C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('18','CUBE 647-100C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('19','CUBE 660-60C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('20','CUBE 660-100C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('21','CUBE 730-30C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('22','DIAMOND C-Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('23','DIAMOND C-20A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('24','DIAMOND C-20A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('25','DIAMOND C-30A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('26','DIAMOND C-30A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('27','DIAMOND C-30A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('28','DIAMOND C-30L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('29','DIAMOND C-30L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('30','DIAMOND C-40A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('31','DIAMOND C-40A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('32','DIAMOND C-40L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('33','DIAMOND C-40L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('34','DIAMOND C-55A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('35','DIAMOND C-55A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('36','DIAMOND C-55L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('37','DIAMOND C-55L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('38','DIAMOND C-70A','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('39','DIAMOND C-70L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('40','DIAMOND Cx-10L 10.6','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('41','DIAMOND Cx-10L 10.2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('42','DIAMOND Cx-10L 9.6','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('43','DIAMOND Cx-10L 9.3','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('44','DIAMOND Cx-10LDE+ 10.6','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('45','DIAMOND Cx-10LDE+ 10.2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('46','DIAMOND Cx-10LDE+ 9.6','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('47','DIAMOND Cx-10LDE+ 9.3','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('48','DIAMOND GEM-Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('49','DIAMOND GEM-100L 9.6','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('50','DIAMOND GEM-100L 10.2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('51','DIAMOND GEM-100L 10.6','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('52','Genesis Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('53','Genesis CX-Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('54','Genesis CX SLM-Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('55','Genesis CX STM Compact (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('56','Genesis CX STM-Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('57','Genesis MX MTM-Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('58','Genesis MX SLM-Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('59','Genesis MX STM-Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('60','Genesis Taipan 460 nm to 577 nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('61','Genesis Taipan 607 nm to 639 nm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('62','Genesis CX355 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('63','Genesis CX460 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('64','Genesis CX480 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('65','Genesis CX488 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('66','Genesis CX514 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('67','Genesis CX532 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('68','Genesis CX561 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('69','Genesis CX577 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('70','Genesis CX590 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('71','Genesis CX355 STM Compact (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('72','Genesis CX355 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('73','Genesis CX460 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('74','Genesis CX480 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('75','Genesis CX488 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('76','Genesis CX514 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('77','Genesis CX532 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('78','Genesis CX532 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('79','Genesis CX561 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('80','Genesis CX577 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('81','Genesis CX590 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('82','Genesis MX460 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('83','Genesis MX480 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('84','Genesis MX488 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('85','Genesis MX514 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('86','Genesis MX532 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('87','Genesis MX561 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('88','Genesis MX577 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('89','Genesis MX590 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('90','Genesis MX460 SLM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('91','Genesis MX480 SLM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('92','Genesis MX488 SLM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('93','Genesis MX514 SLM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('94','Genesis MX532 SLM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('95','Genesis MX561 SLM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('96','Genesis MX577 SLM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('97','Genesis MX590 SLM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('98','Genesis MX460 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('99','Genesis MX480 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('100','Genesis MX488 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('101','Genesis MX514 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('102','Genesis MX532 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('103','Genesis MX561 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('104','Genesis MX577 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('105','Genesis MX590 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('106','Genesis MX607 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('107','Genesis MX639 STM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('108','Genesis MX460 STM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('109','Genesis MX480 STM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('110','Genesis MX488 STM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('111','Genesis MX514 STM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('112','Genesis MX532 STM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('113','Genesis MX561 STM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('114','Genesis MX577 STM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('115','Genesis MX590 STM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('116','Genesis MX460 MTM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('117','Genesis MX480 MTM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('118','Genesis MX488 MTM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('119','Genesis MX514 MTM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('120','Genesis MX532 MTM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('121','Genesis MX561 MTM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('122','Genesis MX577 MTM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('123','Genesis MX590 MTM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('124','Genesis MX607 MTM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('125','Genesis MX639 MTM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('126','Genesis MX920 MTM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('127','Genesis MX1064 MTM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('128','Genesis MX1154 MTM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('129','Genesis MX460 MTM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('130','Genesis MX480 MTM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('131','Genesis MX488 MTM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('132','Genesis MX514 MTM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('133','Genesis MX532 MTM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('134','Genesis MX561 MTM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('135','Genesis MX577 MTM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('136','Genesis MX590 MTM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('137','Genesis MX607 MTM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('138','Genesis MX639 MTM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('139','Genesis MX920 IR MTM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('140','Genesis MX1064 IR MTM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('141','Genesis MX1154 IR MTM (OEM)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('142','Genesis Taipan 460','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('143','Genesis Taipan 480','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('144','Genesis Taipan 488','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('145','Genesis Taipan 514','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('146','Genesis Taipan 532','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('147','Genesis Taipan 561','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('148','Genesis Taipan 577','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('149','Genesis Taipan 607','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('150','Genesis Taipan 639','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('151','Genesis Taipan HD-Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('152','Genesis Taipan HD 460-2000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('153','Genesis Taipan HD 480-2000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('154','Genesis Taipan HD 488-3000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('155','Genesis Taipan HD 532-3000/5000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('156','Genesis Taipan HD 577-3000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('157','Genesis Taipan HD 590-2000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('158','Innova 300C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('159','Innova 300C I-304','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('160','Innova 300C  I-305','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('161','Innova 300C  I-306','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('162','Innova 300C  I-307','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('163','Innova 300C  I-308','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('164','Innova FreD','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('165','Innova 300 C MotoFred (SHG)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('166','Innova 300 C MotoFred (Fundamental)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('167','Innova 300 C MotoFred (High-Power Option)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('168','Innova 90C FRED (SHG)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('169','Innova 90C FRED (Fundamental)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('170','Innova Sabre MotoFred (SHG)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('171','Innova Sabre MotoFred (Fundamental)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('172','Innova 70C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('173','Innova 70 Spectrum','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('174','Innova 70C -3','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('175','Innova 70C -4','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('176','Innova 70C -5','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('177','Innova 70C-K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('178','Innova 70C-K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('179','Innova 90C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('180','Innova 90C -A3','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('181','Innova 90C -A4','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('182','Innova 90C -A4','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('183','Innova 90C-A5','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('184','Innova 90C-A5','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('185','Innova 90C-A6','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('186','Innova 90C-A6','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('187','Innova 90C-K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('188','Innova 90C-K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('189','Innova 90C-K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('190','Innova 90C-K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('191','Innova 90C-K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('192','Innova Sabre','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('193','Innova Sabre DBW-10','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('194','Innova Sabre DBW-15','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('195','Innova Sabre DBW-20','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('196','Innova Sabre DBW-25','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('197','Innova Sabre TSM-10','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('198','Innova Sabre TSM-15','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('199','Innova Sabre TSM-20','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('200','Innova Sabre TSM-25','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('201','Innova Sabre Kryption DBW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('202','Innova Sabre Kryption DBW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('203','Innova Sabre Kryption DBW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('204','Innova Sabre Kryption DBW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('205','Innova Sabre Kryption DBW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('206','Innova Sabre Kryption DBW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('207','Innova Sabre Kryption DBW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('208','Innova Sabre Kryption DBW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('209','Magnum II Laser','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('210','Magnum II-500','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('211','Magnum II-500','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('212','Magnum II-1000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('213','Magnum II-1500','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('214','Magnum II-2000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('215','Magnum II-4000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('216','Magnum II-7000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('217','Magnum 680','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('218','Magnum 808','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('219','Mini Laser','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('220','Mini 640','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('221','Mini 660','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('222','Mini 685','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('223','Mini 785','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('224','Mini-501L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('225','Mini-701L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('226','Mini-503L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('227','Mini-703L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('228','Mini-505L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('229','Mini-705L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('230','Mini-509L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('231','Mini-709L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('232','Mini-511L (Custom)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('233','Mini-711L (Custom)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('234','Mini-515L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('235','Mini-715L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('236','Mini-519L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('237','Mini-719L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('238','Mini-533L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('239','Mini-733L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('240','Mini-599L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('241','Mini-799L','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('242','Mini-501S (Custom)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('243','Mini-504G','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('244','Mini-501H','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('245','Mini-507X','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('246','Mini-519X','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('247','Mini-Custom','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('248','OBIS Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('249','OBIS LX/LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('250','OBIS LX/LS FP (Fiber-Pigtailed)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('251','OBIS 375LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('252','OBIS405LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('253','OBIS 413LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('254','OBIS 422LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('255','OBIS 445LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('256','OBIS458LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('257','OBIS473LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('258','OBIS 488LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('259','OBIS 488LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('260','OBIS 505LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('261','OBIS 505LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('262','OBIS 514LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('263','OBIS 514LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('264','OBIS 520LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('265','OBIS 532LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('266','OBIS 552LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('267','OBIS 561LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('268','OBIS 594LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('269','OBIS 637LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('270','OBIS 640LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('271','OBIS 647LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('272','OBIS 660LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('273','OBIS 685LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('274','OBIS 730LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('275','OBIS 752LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('276','OBIS 785LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('277','OBIS 808LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('278','OBIS 980LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('279','OBIS FP 405LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('280','OBIS FP 413LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('281','OBIS FP 445LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('282','OBIS FP 473LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('283','OBIS FP 488LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('284','OBIS FP 488LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('285','OBIS FP 505LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('286','OBIS FP 514LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('287','OBIS FP 514LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('288','OBIS FP 520LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('289','OBIS FP 532LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('290','OBIS FP 552LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('291','OBIS FP 561LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('292','OBIS FP 594LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('293','OBIS FP 637LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('294','OBIS FP 640LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('295','OBIS FP 647LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('296','OBIS FP 660LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('297','OBIS CORE LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('298','OBIS CORE 488LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('299','OBIS CORE 505LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('300','OBIS CORE 514LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('301','OBIS CORE 532LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('302','OBIS CORE 552LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('303','OBIS CORE 561LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('304','OBIS CORE 594LS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('305','OBIS CellX Laser Beam Combiner','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('306','OBIS CellX-405','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('307','OBIS CellX-488','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('308','OBIS CellX-561','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('309','OBIS CellX-637','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('310','OBIS LG Ultraviolet Laser','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('311','OBIS LG 355-20','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('312','OBIS LG 355-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('313','PowerLine Laser','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('314','PowerLine 445','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('315','PowerLine 670','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('316','PowerLine 808','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('317','Sapphire Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('318','Sapphire FP (Fiber-Pigtailed)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('319','Sapphire 458 FP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('320','Sapphire 488 FP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('321','Sapphire 514 FP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('322','Sapphire 532 FP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('323','Sapphire 552 FP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('324','Sapphire 561 FP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('325','Sapphire 588 FP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('326','Sapphire 594 FP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('327','Sapphire LP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('328','Sapphire 458 LP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('329','Sapphire 488 LP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('330','Sapphire 514 LP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('331','Sapphire 532 LP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('332','Sapphire 552 LP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('333','Sapphire 561 LP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('334','Sapphire 568 LP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('335','Sapphire 588 LP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('336','Sapphire 594 LP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('337','Sapphire 488 LPX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('338','Sapphire 532 LPX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('339','Sapphire 561 LPX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('340','Sapphire SF (Single-Frequency)','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('341','Sapphire 488 SF','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('342','Sapphire 532 SF','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('343','StingRay and BioRay Laser Diode Modules','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('344','StingRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('345','StingRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('346','StingRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('347','StingRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('348','StingRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('349','StingRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('350','StingRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('351','StingRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('352','StingRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('353','BioRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('354','BioRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('355','BioRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('356','BioRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('357','BioRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('358','BioRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('359','BioRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('360','BioRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('361','BioRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('362','BioRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('363','BioRay','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('364','BioRay FR','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('365','BioRay FR','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('366','BioRay FR','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('367','BioRay FR','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('368','Verdi V Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('369','Verdi V2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('370','Verdi V6','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('371','Verdi V8','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('372','Verdi V10','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('373','Verdi V12','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('374','Verdi V18','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('375','Verdi G Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('376','Verdi G2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('377','Verdi G5','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('378','Verdi G7','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('379','Verdi G8','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('380','Verdi G10','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('381','Verdi G12','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('382','Verdi G15','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('383','Verdi G18','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('384','Verdi G20','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('385','Verdi G2 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('386','Verdi G5 SLM','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('387','DIAMOND E-Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('388','DIAMOND E-1000','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('389','DIAMOND E-1000i','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('390','DIAMOND J-Series','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('391','CO Laser - 5µm','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('392','DIAMOND J-3-5 CO Laser','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('393','DIAMOND J-2-9.4','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('394','DIAMOND J-2-10.6','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('395','DIAMOND J-3-9.4','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('396','DIAMOND J-3-10.2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('397','DIAMOND J-3-10.6','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('398','DIAMOND J-5-9.4','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('399','DIAMOND J-5-10.2','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('400','DIAMOND J-5-10.6','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('401','DIAMOND J-5-10.6NB','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('402','AVIA NX Family of Compact DPSS Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('403','AVIA NX 532-36','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('404','AVIA NX 532-45','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('405','AVIA NX 532-65','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('406','AVIA NX 532-85','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('407','AVIA NX 532-65 HPE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('408','AVIA NX 532-85 HPE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('409','AVIA NX 355-20','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('410','AVIA NX 355-25','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('411','AVIA NX 355-30','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('412','AVIA NX 355-40','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('413','AVIA NX 355-55','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('414','AVIA LX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('415','AVIA LX 355-20','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('416','ExciStar XS','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('417','ExciStar XS 200','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('418','ExciStar XS 500','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('419','ExciStar XS 200','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('420','ExciStar XS 500','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('421','ExciStar XS 200','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('422','ExciStar XS 500','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('423','ExciStar XS 200','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('424','ExciStar XS 500','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('425','HYPER RAPID','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('426','HyperRapid 100 P1064','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('427','HyperRapid 100 P532','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('428','HyperRapid 100 355-SW 355','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('429','HyperRapid 100 355-SW 532','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('430','HyperRapid 100 355-SW 1064','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('431','HyperRapid 50 1064','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('432','HyperRapid 50 532','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('433','HyperRapid 50 355','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('434','HyperRapid 50 HE 1064','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('435','HyperRapid 50 HE 532','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('436','HyperRapid 50 HE 355','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('437','HyperRapid NX','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('438','HyperRapid NX 1064-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('439','HyperRapid NX 1064-100','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('440','HyperRapid NX 532-25','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('441','HyperRapid NX 532-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('442','HyperRapid NX 355-15','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('443','HyperRapid NX 355-30','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('444','HyperRapid NX SmartCleave 1064-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('445','HyperRapid NX SmartCleave 1064-100','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('446','IndyStar 193 - 1 kHz','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('447','IndyStar 193 - 2 kHz','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('448','IndyStar 248 - 2 kHz','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('449','IndyStar 248 - 1 kHz','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('450','IndyStar','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('451','LEAP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('452','LEAP 80K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('453','LEAP 130K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('454','LEAP 80C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('455','LEAP 130C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('456','LEAP 100K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('457','LEAP 150K','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('458','LEAP 100C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('459','LEAP 150C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('460','LEAP 300C','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('461','LPXpro','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('462','LPFpro 205-157','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('463','LPFpro 205-193','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('464','LPFpro 220-157','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('465','LPFpro 220 -193','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('466','LPXPro 210-193','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('467','LPXPro 210-248','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('468','LPXPro 210-308','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('469','LPXPro 210-351','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('470','LPXpro 240-193','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('471','LPXpro 240-248','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('472','LPXpro 240-351','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('473','LPXpro 305-193','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('474','LPXpro 305-248','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('475','LPXpro 305-308','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('476','LPXpro 305-351','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('477','LPXPro 220-193','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('478','LPXpro220-248','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('479','LPXpro220-308','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('480','LPXpro220-351','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('481','MATRIX CW Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('482','MATRIX 1064 CW','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('483','MATRIX QS DPSS Lasers','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('484','MATRIX 1064 1-LP','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('485','MATRIX 1064-7-10','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('486','MATRIX 1064-10-30','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('487','MATRIX 355-M1','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('488','MATRIX 355-1-60','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('489','MATRIX 355-5-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('490','MATRIX 355-8-50','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('491','MATRIX 355-1-60 BE','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('492','MATRIX 532-7-30','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('493','MATRIX 532-8-100','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('494','MATRIX 532-14-40','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('495','RAPID','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('496','RAPID-1064','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('497','RAPID-532','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('498','RAPID-355','');
INSERT INTO `pd_products_general_beta` (`ID`,`Name`,`Acquired_Site`) VALUES ('499','RAPID NX','');
